### PR TITLE
add new /v1/peers endpoints to the api

### PR DESCRIPTION
**Pull request by antiochp**
* GET /v1/peers/all
* GET /v1/peers/connected

`all` is from the `peer_store`
`connected` is from the `p2p_server`

```
curl 127.0.0.1:13413/v1/peers/all
[
  {
    "addr": "127.0.0.1:14414",
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "flags": "Healthy"
  }
]
```

```
curl 127.0.0.1:13413/v1/peers/connected
[
  {
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "version": 1,
    "addr": "127.0.0.1:14414",
    "total_difficulty": 37
  }
]
```

### CODE REVIEW

**Comment by ignopeverell** [comment]
This works and will return all known peers. We may want a filter that only shows currently connected peers (available through the p2p server).

**Comment by antiochp** [comment]
Interesting observation, start to see results like this after a while (maybe after nodes are restarted but not sure) -

```
curl 127.0.0.1:13413/v1/peers/connected
[
  {
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "version": 1,
    "addr": "127.0.0.1:14414",
    "total_difficulty": 37
  },
  {
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "version": 1,
    "addr": "127.0.0.1:14414",
    "total_difficulty": 37
  },
  {
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "version": 1,
    "addr": "127.0.0.1:14414",
    "total_difficulty": 37
  }
]
```

**Comment by antiochp** [comment]
Actually not even from restarts, just leaving a couple of nodes running for a few minutes - 

```
curl 127.0.0.1:13413/v1/peers/connected
[
  {
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "version": 1,
    "addr": "127.0.0.1:14414",
    "total_difficulty": 37
  },
  {
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "version": 1,
    "addr": "127.0.0.1:14414",
    "total_difficulty": 37
  },
  {
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "version": 1,
    "addr": "127.0.0.1:14414",
    "total_difficulty": 37
  },
  {
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "version": 1,
    "addr": "127.0.0.1:14414",
    "total_difficulty": 37
  },
  {
    "capabilities": {
      "bits": 7
    },
    "user_agent": "MW/Grin 0.1",
    "version": 1,
    "addr": "127.0.0.1:14414",
    "total_difficulty": 37
  }
]
```

**Comment by ignopeverell** [comment]
The duplicates look like a bug. Want to create an issue?

**Pull request merged**
