### PR TITLE
Update translation links and naming scheme

### PR DESCRIPTION
**Pull request by oliversimon**

### CODE REVIEW

**Comment by sesam** [comment]
LGTM.
:+1: Also the German grammar improvements makes the formulations appear more native. Ping @hendi if you have a minute :), any comment on the [German translation changes](https://github.com/mimblewimble/grin/pull/2357/files#diff-f91467498c221e7a37c79dccf99a07b5) before merge?

**Comment by Problemchild1** [comment]
Thanks for the update

**Comment by hendi** [comment]
LGTM :+1:

**Comment by yeastplume** [comment]
Thank you!

**Pull request merged**
