### PR TITLE
Fixing coverage for modules

### PR DESCRIPTION
**Pull request by percytheprefect**
Fixing bug in .yml file

Adding cargo test --no-run command to after_success

Removing comment, adding pwd to see what working directory is

Debugging working directory for .yml file

Replacing binutils with libbfd-dev

Removing libbfd-dev because it fails the build

Adding test coverage to rest of grin modules

fix code coverage

fix merge conflict

### CODE REVIEW

**Comment by ignopeverell** [comment]
Report still looks mostly empty, is that expected?

**Comment by sesam** [comment]
I also get 0% all the way when locally trying `cargo cov build; cargo cov report --open`

If this is unexpected, I found one possible method to get coverage numbers more manually; probably doing something very similar to what cov or kcov does, but step by step, so might be easier to find any problematic parts. I haven't had time to try, so I'll just leave the link here https://jbp.io/2017/07/19/measuring-test-coverage-of-rust-programs

**Comment by percytheprefect** [comment]
@sesam I believe I have this fixed and working. Could you try locally?

**Comment by sesam** [comment]
@percytheprefect I checked out your branch and did `cargo cov build; cargo cov report` but in target/cov/report/index.html I only get 0% all the way.
How do you do, and what kind of coverage output do you get? Maybe a screenshot teaser? :)

**Comment by percytheprefect** [comment]
@sesam Please follow the instructions in the .travis.yml file -- you should only need to start on this line: 

https://github.com/mimblewimble/grin/pull/547/files#diff-354f30a63fb0907d4ad57269548329e3R51

**Comment by sesam** [comment]
@percytheprefect I tried once on a Macbook, but kcov is linux-only. Now trying on a debian, though this part

````
sudo make install &&
  cd ../.. &&
  rm -rf kcov-master
````

disturbs me a bit. Some people 💃  might not want to give root away to a recently built program, then immediately aftewards remove all traces of what was just installed... 🤕

**Comment by percytheprefect** [comment]
@sesam I have re-worked the `.travis.yml` file to remove that line. Unfortunately the original author of the blog post I was following seemed to adding some extra commands that were not necessary. 

http://sunjay.ca/2016/07/25/rust-code-coverage

**Comment by ignopeverell** [comment]
Going to merge as:
1. It can't make things worse.
2. I'm tired of seeing all these empty reports on PRs.

**Comment by ignopeverell** [comment]
We're still getting zero coverage info and it's slowing down the build quite a bit. Any fix? Or should I remove it for now?

**Pull request merged**
