### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jacqlu**

### CODE REVIEW

**Comment by ignopeverell** [comment]
A Spanish translation would be better as its own file, perhaps `README.md.es`? Also can you confirm this isn't just Google translate?

**Comment by quentinlesceller** [comment]
Pretty sure it's Google translate (e.g. "sonrisa" instead of "Grin").

**Comment by knocte** [comment]
I'm a native Spanish speaker, I confirm this is not a good translation.

**Comment by quentinlesceller** [comment]
Closing then.

**Pull request closed without merging**
