### PR TITLE
[WIP] Handle txhashset failure

### LINKED ISSUE #1293: [sync] remaining issues
lehnberg @lehnberg 17:12

```
FYI, built the latest from master just now and removed .grin as discussed before, this time around I synced seamlessly. Can’t have taken me more than five minutes. ✌️
git fetch upstream
git merge upstream/master
cargo clean
cargo build --release
rm -rf .grin
RUST_BACKTRACE=1 ./target/release/grin
```

Gary Yu @garyyu 17:34
`less than 5 minutes is also odd :) do you have a powerful PC? even the fastsync mode, the validation procedure is slow on my mac air. will measure how long I need.`

Gary Yu @garyyu 19:08
```
@lehnberg I’m not lucky, fastest time I need 15 minutes to sync. so it’s possible your MBP 2016 is 3 times faster than my macpro 2013.
and sync procedure still buggy :(
I tested 2 times:
1st time on my poor old mac:

- spent 2’30” for header download,
- spent 5 minutes to download the TxHashsets, ( not lucky! could download from a very slow peer! )
- spent 7' to validate chain state,
- spent 24 minutes to download remaining blocks and finish syncing. (buggy here! paused for a * while no any blocks coming and force to quit and start again).

2nd time, on a mac pro 2013

- spent 1’46” for header download,
- spent 6" to download the TxHashsets, (buggy here! paused for Error summing and verifying kernel sums, and have to force quit and start again, 6 seconds is for 2nd time).
- spent 8' to validate chain state,
- spent 5’30" to download remaining blocks and finish syncing.

```

### PR DESCRIPTION
**Pull request by hashmap**
Allow fast sync to recover if txhashset download or verifiaction fails
Partially fixes #1293

### CODE REVIEW

**Comment by garyyu** [comment]
@hashmap You're fast 👍  
actually I just complete the first partial fix last night and test is just finished :)

And some review comments for your fix:

1. Is it a good idea to force `SyncState` change? If in any case another state is working, that will break it forcibly.
2. Instead, I would like to communicate error of syncing, and let sync thread control state on its own pace.
3. I saw a lot of unnecessary or not-related code changes in this pull-request. It's a good thing to refactor the code and give optimization from time to time, but better to manage it in separate PR. It's easier to review the code change when only related fix are there.

If needed, I can still submit my pull-request today, just let me know:)

**Comment by hashmap** [comment]
@garyyu feel free to submit your PR, I sketched out this one last night, it's still work in progress. I push code as early as possible -a headsup to avoid effort duplication like in this case:) No rush, take your time.

1. It's a sketch to see how it works, I think it should be implemented here https://github.com/mimblewimble/grin/blob/master/servers/src/common/types.rs#L337

2. It seems in this case you need to kinda duplicate the purpose of status?

3. It was done by our Whitespace Overlord aka rustfmt, it's annoying but it's a necessary evil.

**Comment by garyyu** [comment]
@hashmap  my one is already there https://github.com/mimblewimble/grin/pull/1322, please take a review on it if having time, thanks:)

**Comment by hashmap** [comment]
Closed in favour of #1322

**Pull request closed without merging**
