### PR TITLE
cleanup unused archive_mode param

### PR DESCRIPTION
**Pull request by antiochp**

### CODE REVIEW

**Comment by garyyu** [comment]
So, I think that configuration item can be removed?
```
#run the node in "full archive" mode (default is fast-sync, pruned node)
archive_mode = false
```

Also the `Bit flags for FULL_NODE`.

**Comment by ignopeverell** [comment]
Might have merged too quickly. Want to add a PR for these @garyyu ?

**Comment by garyyu** [comment]
OK 😄

**Comment by antiochp** [comment]
No don't remove that - we still use it...

And the `bitflags` are not used but I think still useful to have as a placeholder (all nodes are back to being `FULL_NODES` today).

**Comment by garyyu** [comment]
> No don't remove that - we still use it...

@antiochp   Do you mean you want to use this config item only for `compact_blocks_db`?
If so, then perhaps the comments here `#run the node in "full archive" mode (default is fast-sync, pruned node)` is not correct.

**Comment by antiochp** [comment]
Yes that comment is incorrect now.
It should probably be something along the lines of "Preserve historical blocks in the db?".

**Pull request merged**
