### PR TITLE
Hard fork tryout: better PoW encapsulation in block header

### PR DESCRIPTION
**Pull request by ignopeverell**
Introducing a struct to encapsulate all PoW fields. This has the effect to reorder block header fields.

### CODE REVIEW

**Comment by tromp** [comment]
Will it also add the scaling factor for secondary PoW?

**Comment by ignopeverell** [comment]
Just add it and keep it unused for now? Wasn't planning on adding seconday PoW validation, factor adjustment, etc

**Comment by tromp** [comment]
Yep; just add "for future use". Makes hard-fork slightly more interesting due to change in header size.

**Comment by ignopeverell** [comment]
Alright then, I'll add that up.

**Comment by ignopeverell** [comment]
Ready for review from whoever wants to.

**Pull request merged**
