### PR TITLE
Use latest hosted agent for CI

### PR DESCRIPTION
**Pull request by quentinlesceller**
Which are:
macOS 10.15 Catalina
Ubuntu 18.04 LTS
Windows server 2019

- Use `ubuntu-latest`, `macos-latest` and `windows-latest`.
- Remove the shared install steps.

Build should be a bit faster.

more info here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#software

### CODE REVIEW

**Comment by jaspervdm** [comment]
Looks good, although I'm a bit careful about changing stuff like this since croaring is pretty picky about versions etc. Have you tried creating a binary on the new OS, does it run fine?

Actually on second thought: are we sure we want to use `-latest` for everything? I'm expecting it might break our CI randomly in the future when a new version is out

**Comment by quentinlesceller** [comment]
I haven't tried to create a binary.

Regarding the `latest`, we can expect at most once a year some issue with the CI. This is using only stable release.

**Comment by quentinlesceller** [comment]
I'll try a release on my repo later today to see how it goes.

**Comment by quentinlesceller** [comment]
Release working well @jaspervdm https://github.com/quentinlesceller/grin/releases/tag/v3.1.2-test.1

**Pull request merged**
