### PR TITLE
Minor wallet recover fixes

### PR DESCRIPTION
**Pull request by ignopeverell**
Couple of those are security sensitive:

1. Do not log the recovery phrase on error.
2. Prompt for the phrase instead of passing it as a command arg so it doesn't appear in any command line history.

### CODE REVIEW

**Comment by yeastplume** [comment]
Good catch on log. I tried to fix the recovery phrase issue earlier in the same way, but found it a bit problematic from a UX experience, see: https://github.com/mimblewimble/grin/issues/2174

Basically, (at least on my system) stdin ignores any keymaps, so any attempt to erase or hit arrow keys as you're typing just creates a bigger mess. Agreed doing it this way is better than leaving it in your shell history, but still.. hmm..

**Comment by yeastplume** [comment]
1) ____ 2) ____ 3) _____ (print to 12 or 24)
(Q to quit, 1-24 to edit a word)

Type word 1 > pants

1) pants 2) ____ 3) _____ (print to 12 or 24)
(Q to quit, 1-24 to edit a word)

Type word 2 > yeast


Something like this? And bonus points if we can figure out the equivalent of typing ‘stty erase <backspace>’, to ensure delete works

**Comment by ignopeverell** [comment]
Ah, missed #2174. Not sure what's this UX thing you're talking about though.

Btw, hate to keep adding more dependencies but isn't that what readline is for? We could pick a Rust port (like https://github.com/murarth/linefeed).

**Comment by yeastplume** [comment]
Only problem with that linefeed crate is that I didn’t know it existed until now.

**Comment by ignopeverell** [comment]
Superseded by #2276

**Pull request closed without merging**
