### PR TITLE
compare genesis during peering handshake

### PR DESCRIPTION
**Pull request by antiochp**
- [x] make sure we have genesis when setting up the handshake
- [x] pass genesis in `hand ->`
- [x] pass genesis in `shake <-`
- [x] check genesis for mismatch and `Defunct` the peer
- [x] test this is "backward compatible" by not breaking existing nodes (handshake ser/deser changed)

This will split the network - see comment below.
"old" and "new" nodes will not peer successfully with each other.

### CODE REVIEW

**Comment by antiochp** [comment]
This is definitely no backward compatible.
An "existing" node (no genesis hash expected in handshake) connecting to a peer or seed and receiving a handshake with a genesis hash serialized in it does this - 

```
Nov 19 16:19:27.161 DEBG Connecting to seed: 127.0.0.1:13414.
Nov 19 16:19:27.161 DEBG New peer address to connect to: 127.0.0.1:13414.
Nov 19 16:19:27.162 DEBG 0.0.0.0:14414 connecting to 127.0.0.1:13414
Nov 19 16:19:27.264 DEBG saving peer to store PeerData { addr: V4(127.0.0.1:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Defunct }
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /Users/travis/build/rust-lang/rust/src/liballoc/vec.rs:1555:10
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic_bounds_check
   9: <alloc::vec::Vec<T> as core::ops::index::Index<usize>>::index
  10: <grin_p2p::msg::SockAddr as grin_core::ser::Readable>::read
  11: <grin_p2p::msg::Hand as grin_core::ser::Readable>::read
  12: grin_core::ser::deserialize
  13: grin_p2p::msg::read_msg::{{closure}}
  14: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}::{{closure}}
  15: <core::result::Result<T, E>>::map
  16: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}
  17: <futures::future::chain::Chain<A, B, C>>::poll
  18: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  19: <alloc::boxed::Box<F> as futures::future::Future>::poll
  20: <futures::future::chain::Chain<A, B, C>>::poll
  21: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  22: <futures::future::chain::Chain<A, B, C>>::poll
  23: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  24: <alloc::boxed::Box<F> as futures::future::Future>::poll
  25: <futures::future::chain::Chain<A, B, C>>::poll
  26: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  27: <alloc::boxed::Box<F> as futures::future::Future>::poll
  28: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  29: <alloc::boxed::Box<F> as futures::future::Future>::poll
  30: <alloc::boxed::Box<F> as futures::future::Future>::poll
  31: <futures::future::select::Select<A, B> as futures::future::Future>::poll
  32: <futures::future::chain::Chain<A, B, C>>::poll
  33: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  34: <alloc::boxed::Box<F> as futures::future::Future>::poll
  35: <futures::future::chain::Chain<A, B, C>>::poll
  36: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  37: <futures::future::chain::Chain<A, B, C>>::poll
  38: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  39: <alloc::boxed::Box<F> as futures::future::Future>::poll
  40: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
  41: <futures::task_impl::Spawn<T>>::enter::{{closure}}
  42: futures::task_impl::std::set
  43: <futures::task_impl::Spawn<T>>::enter
  44: <futures::task_impl::Spawn<T>>::poll_future_notify
  45: tokio_core::reactor::Core::dispatch_task::{{closure}}
  46: <scoped_tls::ScopedKey<T>>::set
  47: tokio_core::reactor::Core::dispatch_task
  48: tokio_core::reactor::Core::dispatch
  49: tokio_core::reactor::Core::poll
  50: tokio_core::reactor::Core::run
  51: grin_grin::server::Server::start
  52: grin::server_command
  53: grin::main
  54: __rust_maybe_catch_panic
  55: std::rt::lang_start
  56: main
```

@ignopeverell thoughts on this?
On one hand this is bad as it actually kills nodes.
On the other is stops the risk of a hard fork in the network by killing all the old nodes...

Related - we should probably revisit the various serialization/deserialization stuff at the p2p layer to prevent panics like this?

**Comment by antiochp** [comment]
Reworked this to preserve the order of the fields so the new `genesis` field is on the end of the serialized byte array. 

We see this on a "new" node when an "old" node tries to connect -
```
Nov 19 22:22:01.999 DEBG New peer address to connect to: 127.0.0.1:14414.
Nov 19 22:22:02.002 DEBG saving peer to store PeerData { addr: V4(127.0.0.1:14414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Defunct }
Nov 19 22:22:08.859 INFO Client error: Serialization(IOErr(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) }))
```

And we see this on an "old" node when a "new" node tries to connect (handshake fails on "new" node like above) -
 
```
Nov 19 22:22:02.001 DEBG Success handshake with 127.0.0.1:13414.
Nov 19 22:22:02.001 DEBG Saving newly connected peer 127.0.0.1:13414.
Nov 19 22:22:02.002 DEBG saving peer to store PeerData { addr: V4(127.0.0.1:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Healthy }
Nov 19 22:22:02.009 INFO Client 127.0.0.1:13414 connection lost: Connection(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("early eof") }) })
Nov 19 22:22:08.856 DEBG monitoring peers (1)
Nov 19 22:22:08.856 DEBG cleaning V4(127.0.0.1:13414), not connected
```

**Comment by antiochp** [comment]
@ignopeverell tested various peering handshakes between "old" and "new" nodes.
Both nodes stay up and survive the failed handshake.
Neither node peers successfully with the other (the "new" node always fails with a serialization error when reading the old style `hand` or `shake`).

This will split the network once we deploy >=1 nodes with this change?
"old" nodes will no longer peer with "new" nodes and vice-versa.

Thoughts on deploying this on testnet1?

**Comment by ignopeverell** [comment]
I do have thoughts: I don't think we can. With a split network, we'll have a long fork situation (which could have been good for testing) and bad peering on one side or another for some time. We could try a "big bang" upgrade where we try to warn everyone and get them to update ASAP but I'm not sure it's worth the trouble. This will become most useful with testnet2 anyway, when we have more than one network. What do you think?

**Comment by antiochp** [comment]
Yeah - was thinking a bit more about this. This only benefit we would get would be from testing a long fork situation and as you say probably not worth it.
This is basically something we want in place for testnet2 (it effectively _is_ testnet2 - start with a new genesis and require peers to redeploy to join the new network).

So - happy to merge this on master and have it in place for when testnet2 goes live?

**Comment by ignopeverell** [comment]
Looks good! And thanks for cleaning up some of my code too :-)

**Pull request merged**
