### PR TITLE
feature: txhashset downloading progress display on tui

### PR DESCRIPTION
**Pull request by garyyu**
To close https://github.com/mimblewimble/grin/issues/1702

The txhashset archive file is more and more bigger when height increasing, now in testnet3, it's near to 150M bytes, so the download procedure is quite long.

This PR give a progress status display on TUI, with 3 main info:
- Total size of this downloading archive
- Percentage of downloaded
- Average speed on kB/s

### CODE REVIEW

**Comment by garyyu** [comment]
Here is it looks like:
screen shot 2018-10-12 at 8 40 49 am

**Comment by ignopeverell** [comment]
Fancy!

**Comment by ignopeverell** [comment]
@garyyu looks like the cherrypick bot failed to merge this cleanly, can you make sure it gets merged into T4? Thanks!

**Comment by garyyu** [comment]
Don't worry, Let me give a manual cherry pick merge.

**Pull request merged**
