### PR TITLE
Revert "move siphash out of pow and into util"

### PR DESCRIPTION
**Pull request by antiochp**
Reverts mimblewimble/grin#633 (this siphash impl is specific to cuckoo/pow).
We are going to use a more general purpose impl for short ids.

### CODE REVIEW

**Comment by ignopeverell** [comment]
Uh, I think you accidently reverted #631 as well?

**Comment by antiochp** [comment]
What is going on here? 
I don't understand why that other commit is in there in this PR...
The diffs don't appear to include anything other than what I intended to revert either (there is nothing related to #631 or it reversion in the diff here).

This is what I did to generate this PR - 
* click the "revert button" on my original PR
* merge it...

And clicking on https://github.com/mimblewimble/grin/pull/635/commits/a0793dd3765b73a91d11b07c83a01b1a2a9d681d above shows an empty commit...

So I _think_ we're ok (other than a nasty looking revert commit message).

**Comment by quentinlesceller** [comment]
Yeah it looks like #631 is still there.

**Comment by antiochp** [comment]
Code from #631 is definitely still in master - 
https://github.com/mimblewimble/grin/blob/master/grin/src/seed.rs#L86

This must have been a timing issue or something on github side of things...

**Comment by ignopeverell** [comment]
Ok cool, sorry I should have double-checked the diff.

**Comment by antiochp** [comment]
No worries - it was weird that github included this "extra" commit here...
Thanks for catching and flagging this!

**Pull request merged**
