### PR TITLE
improve: use batch verification for txhashset rangeproof validation (#1321)

### PR DESCRIPTION
**Pull request by garyyu**
Almost 35 times speed optimization totally.

Before:
```
Aug 07 11:35:31.781 DEBG txhashset: verified 23140 rangeproofs, pmmr size 95321, took 1034s
```

Now:
```
Aug 16 09:50:12.435 DEBG txhashset: verified 28278 rangeproofs, pmmr size 121240, took 35s
```

### CODE REVIEW

**Comment by ignopeverell** [comment]
Awesome!

**Comment by yeastplume** [comment]
That's great! Looks like proper failures in the wallet crate though.

**Comment by garyyu** [comment]
@yeastplume   Looked before for that failures in the wallet crate tests, but no problem to test it locally. no idea what's wrong with travis-ci.
```
$ cd wallet
$ cargo test --release
 
running 5 tests
test db_migrate::migrate_db ... ignored
test libwallet::internal::tx::test::output_commitment_equals_input_commitment_on_spend ... ok
test libtx::build::test::blind_simple_tx_with_offset ... ok
test libtx::build::test::blind_simpler_tx ... ok
test libtx::build::test::blind_simple_tx ... ok

test result: ok. 4 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out

running 3 tests
test aggsig_sender_receiver_interaction_offset ... ok
test aggsig_sender_receiver_interaction ... ok
test test_rewind_range_proof ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

running 3 tests
test file_wallet_basic_transaction_api ... ignored
test db_wallet_tx_rollback ... ok
test db_wallet_basic_transaction_api ... ok

test result: ok. 2 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
```

**Comment by ignopeverell** [comment]
I restarted the build and it's still failing so that seems to be a legit failure, so it'd be good to take a look before merging, it's likely to happen in other environments.

**Comment by garyyu** [comment]
Indeed, although I tested on 3 mac and all passed, I can reproduce the failure in Linux, will look into that.

**Comment by garyyu** [comment]
secp256k1-zkp problem, look https://github.com/mimblewimble/rust-secp256k1-zkp/pull/22

On Linux (Mac is OK), 4/17/18/19/20 range proofs batch verification always fail.

Need dig deeper into the `c` code again~

**Comment by garyyu** [comment]
root cause addressed, similar `"does not live long enough"` rust type of mistakes, will provide fix to `rust-secp256k1-zkp` soon.

**Comment by garyyu** [comment]
PR: https://github.com/mimblewimble/rust-secp256k1-zkp/pull/23  should fix this failure.

**Pull request merged**
