### PR TITLE
Add doc/table_of_contents.md

### PR DESCRIPTION
**Pull request by sesam**
Me and friends want to read the code, and were missing an overview of files and folders.

Material for this .md comes from the mail list https://lists.launchpad.net/mimblewimble/msg00024.html and reading code and asking on gitter.

### CODE REVIEW

**Comment by kargakis** [comment]
Nice. Is there a way we can signal PRs that change the structure outlined here to update the doc so that it doesn't get stale over time?

**Comment by ignopeverell** [comment]
That's useful, thanks! Can you just rename the file to something more like dir_structure.md? I first thought it was a table of content for the documentation we have so far.

**Comment by sesam** [comment]
@ignopeverell There's also the option of expanding to the original intent - yes :) - to also list and describe stuff under docs/

Also thinking of a Grin jargon file, but maybe just start with a # Grin Jargon headline in this file?

**Comment by sesam** [comment]
@kargakis Likely there will have to be someone (who me?) that activaly stays on top of keeping docs updated, i.e. whenever you do a 'git pull' and files are added/renamed/moved it is a good idea to look if somethings should be updated here.

**Comment by ignopeverell** [comment]
@sesam I think that would be a different audience. Describing the repository content is definitely for developers and potential contributors, something that could be a next step after building. However we have a lot of docs that's useful to anyone who'd want to get generally more familiar with the project.

**Comment by sesam** [comment]
I've extracted everything not "documentation structure" to a separate code_structure.md, since that is more aimed at programmers.

**Comment by ignopeverell** [comment]
Perfect, thanks!

**Pull request merged**
