### PR TITLE
BIP39 Support

### PR DESCRIPTION
**Pull request by mcdallas**
Not sure if we need it now, but here it is.

### CODE REVIEW

**Comment by yeastplume** [comment]
Looks very good, thanks for putting this together. Wallet merges are a bit messy at the moment due to upcoming T4, so going to wait a little while to merge this (once I'm ready to merge it on top of https://github.com/mimblewimble/grin/pull/1501)

Hopefully once T4 is up we can incorporate this into the wallet workflow user-side.

**Comment by yeastplume** [comment]
Would you mind rebasing on the current (I think it should just be a matter of the Cargo lock files). I'm kind of of two minds as to whether this should go into the keychain lib or whether it belongs a bit higher up in the wallet (happy to take opinions here).

**Comment by mcdallas** [comment]
Rebased and replaced unmaintained rust-crypto with individual crypto crates (as per #1573)

**Comment by mcdallas** [comment]
@yeastplume maybe it makes more sense to be in the wallet crate but I put it in keychain to contain all the crypto dependencies in there.

**Comment by ignopeverell** [comment]
No strong opinion either way but it does seem a little more keychainy.

**Comment by yeastplume** [comment]
Yeah, of two minds as well. Keeping the deps contained is a good enough argument to keep it keychainy for now, so let's go with that. @mcdallas thanks for putting this together

**Comment by mably** [comment]
Is usage documented somewhere?

**Comment by yeastplume** [comment]
This is just library support, it's not actually integrated into the wallet yet.

**Pull request merged**
