### PR TITLE
[Wait T4]Rustfmt on the all source files

### PR DESCRIPTION
**Pull request by garyyu**
Just launched a global rustfmt by:
```
find ./ -name *.rs | xargs rustfmt  
```

2 purposes on this PR:
1. Make sure all the code is well formatted and good to read.
2. All the coming PR is easier to have the code review, to avoid see all those irrelevant code changes which is caused by `rustfmt`.

For all PRs which is not merged yet at this moment, I'm sorry that you could have to do a merge, if having conflict with this rustfmt.

BTW, my current cargo is 1.29.0 stable version.

### CODE REVIEW

**Comment by garyyu** [comment]
OK, I wait T4 branch.  @yeastplume

**Comment by yeastplume** [comment]
Thanks!

**Comment by ignopeverell** [comment]
Maybe close for now and reopen then? It'd likely be a lot more headache to merge than simply redo.

**Comment by garyyu** [comment]
Ok to close for now 😄 

But please let us indeed DO it in one proper time, with minimum pain but surely can't avoid (since always have working PR), because a good code review help a lot for the quality, and the rustfmt is definitely an evil for the mood of code review.

**Pull request closed without merging**
