### PR TITLE
Provide default values information in generated config file, better handle logging default parameters

### PR DESCRIPTION
**Pull request by glemercier**
Improvements linked to request #3002 

This pull request provides information on default values for each config parameter as comments of the auto-generated `grin-server.toml` file, as per requested in issue mentioned above.
It also better handles cases where some logging parameters are not provided, leading to the program exiting. Instead we use optional parameters set to their default value when absent from the config file.

This PR improves overall configuration experience based on @josef-v feedback but it could be amended to better improve simple configuration inconsistencies coming from anyone else's request.

### CODE REVIEW

**Comment by glemercier** [comment]
Ok I get your point, fair request indeed. I can confirm "serde defaults" are not used everywhere (mostly in one place if I remember well). I'll look into improving this first.

I don't think @josef-v was concerned with the size of the default configuration file as long as he can trim it himself without breaking things. If you think there is a better place to extract and expose the default config values, I'll be happy to look into it.

**Comment by josef-v** [comment]
> #3002 is about having less config file and relying on defaults. Whereas these changes actually increases the size of the generated config file.

I agree with @glemercier that adding another comment is not an issue as you can simply delete it later without any consequences. So having defaults in a comment is ok, maybe unnecessary as we can have the config file generated with defaults and some statement "config file generated with default values" on top of it. However hardcoding these values into config is not a way to go.

> Ideally all this config, specifically the default config would be sourced from one single "source of truth".

That's exactly what I meant.

**Comment by glemercier** [comment]
Thank you both for your feedback and implementation details. I'll work on this and propose an update to this PR.

**Comment by glemercier** [comment]
Update to the PR:
- Use serde defaults on all the config structures. Removed `Option<>` where relevant for cleaner code
- Put all the default values as constants a the top of concerned files. They may be moved to a single dedicated file for a central default config place
- Explicitely implement Serialize/Deserialize for `Capabilities` bitflags
This has for effect that the parameter appears like this in the config file:

```
[server.p2p_config]
capabilities = 15
```

instead of previously

```
[server.p2p_config.capabilities]
bits = 15
```

however it is possible to comment the line in the new case and it will take the default value, which was not possible the old way (using derived Serialize/Deserialize)
 - When generating default config, commenting out all values, since default will be used
 - An (almost) empty config file will work, only the root titles are required to avoid crashing at startup:

```
[server]
[logging]
```

Feel free to provide feedback on this PR and suggest any change.

**Comment by antiochp** [comment]
Planning to take a closer look over this over the next couple of days. But :+1: on the approach.

**Comment by phyro** [comment]
@antiochp this one has accumulated quite a bit of conflicts. Is the proposed change still relevant?

**Pull request closed without merging**
