### PR TITLE
Fix the curve name in one section of intro

### PR DESCRIPTION
**Pull request by hashmap**

### CODE REVIEW

**Comment by GandalfThePink** [comment]
I think that G is just the generating point and not the curve itself. G can be multiplied, i.e. k * G, but C instead is an equation that specified the curve. I think the old version was fine.

**Comment by hashmap** [comment]
@GandalfThePink it seems we both agree that `G` is not the curve. What I'm trying to fix is exactly that statement: `on the elliptic curve _G_,`

**Comment by GandalfThePink** [comment]
Yes, ... I must be colorblind. 

I then fully agree with your modification.

**Comment by kargakis** [comment]
Fixes https://github.com/mimblewimble/grin/issues/2808

**Pull request merged**
