### PR TITLE
fix: move checks for automated test mode into global.rs

### PR DESCRIPTION
**Pull request by JosephGoulden**
Moved some CI checks from pipe.rs to global. I think it makes sense to do this configuration in one place and it looks like the majority of it is done there now. The only real change to the automated tests here is that the genesis block timestamp is 60 minutes in the past rather than the time now.

### CODE REVIEW

**Comment by antiochp** [comment]
I think I created a conflict here touching some adjacent code...

**Comment by JosephGoulden** [comment]
Thanks for review. I fixed the conflicts. Also had to change block time on your new chain_test_helper to 60 from 160, hope that's ok.

**Comment by antiochp** [comment]
We just merged `2.x.x` back into `master`.
Updated base branch for this PR back to `master`.
Once all tests pass I'll merge :+1:.

**Comment by antiochp** [comment]
Getting a windows specific test failure on CI.

**Comment by quentinlesceller** [comment]
Seems like a random failure. Relaunched.

**Pull request merged**
