### PR TITLE
Allow the wallet to be queried for balances and to send a transaction…

### PR DESCRIPTION
**Pull request by camalolo**
… via new handlers

Hello grin masters,

I was playing around with the idea of writing a gui wallet for grin, but I could not find any way to query the balances or send grin units to another wallet. I also am new at rust and I wanted to get familiar with it, and I would be grateful to get your remarks if any.

So I implemented two new handlers for the wallet listener :

/v1/info returns a json encoded struct containing the various balances as calculated in wallet/src/info.rs :

```
> curl http://127.0.0.1:15000/v1/info
{"unspent_total":"150.004500000","unspent_but_locked_total":"150.004500000","unconfirmed_total":"2720.003000000","locked_total":"100.000000000"}
```

/v1/send/transaction expects a json encoded struct containing the details about the transaction to send and returns a json encoded struct with a single boolean value 'confirmed' if there was no error :

```
> curl -H "Content-Type: application/json" -t":"10.000","minimum_confirmations":0,"dest":"http:\/\/127.0.0.1:35000","selection_strategy":"all"}' http://localhost:15000/v1/send/transaction
{"confirmed":true}
```

Finally I reorganized a little the sources in wallet/src so all handlers go to handlers.rs

Obviously this is very crude, and I am not sure you will think it's useful, but it would be an honor to contribute to grin and learn rust while doing that.

Thank you for your time

### CODE REVIEW

**Comment by yeastplume** [comment]
Hi @camalolo .. First thanks for submitting this, this is definitely something that I think will be useful in the future, particularly an API to allow other services/GUIs to access wallet functionality without going through the command line.

Unfortunately, right now a lot of the changes you have here are very soon to be obsoleted due to work on aggsigg (schnorr) which I'll hopefully be integrating in the next couple of weeks (see the changes in https://github.com/mimblewimble/grin/pull/530) In particular, stdout transactions are going away (at least for now,) as the transaction exchange is becoming much more interactive than the simple request/response that exists now.

If we merge this now, it will just create headaches when merging #530 for functionality that will no longer be relevant. Would you mind waiting until that PR is done/merged, then perhaps looking at this again, particularly the send API service as well as a possible handler API cleanup?

**Comment by camalolo** [comment]
No problem, let's check this later !

I think I totally overlooked the security aspect, I should at least ask the password when accepting an info / transaction send request, and maybe it would make more sense to have a separate api port listening on 127.0.0.1 for the wallet operations that need a security check ?

Thank you very much for taking the time to check my pull request !

**Comment by camalolo** [comment]
As an excercise I did what I suggested : I moved the wallet "operations" part to a separate listener that can only listen on 127.0.0.1 and I added a requirement for the passphrase to be sent along with other information. The keychain is derived dynamically at each request so that one cannot use the /info and /transaction/send api calls without knowing the passphrase.

Cheers

**Comment by camalolo** [comment]
Closed this as I seem to have rendered this pull request difficult to read after rebasing the recent commits into my repository. I will create a new pull-request.

**Pull request closed without merging**
