### PR TITLE
Attempt to read ipv4-mapped ipv6 to ipv4 if possible

### PR DESCRIPTION
**Pull request by quentinlesceller**
A potential additional operation during read some maybe not the best idea.

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Only case that I have seen is 3. This PR do the job in that case.

**Comment by antiochp** [comment]
So I think we also need similar logic when we compare ip addrs when looking to see if we are _already_ connected to a peer. 
We do this when accepting a connection (and maybe when trying to connect). If we are already connected then we want to identify the duplicate attempt and close the new connection. And I believe we do this based on a comparison of the ip address.

**Comment by antiochp** [comment]
Related - #3208.

**Comment by antiochp** [comment]
If we can get to point where we are confident this improves the overall situation regarding ipv4-mapped addresses on the network then we should aim to get this merged in for a potential `3.1.0` release.

**Pull request merged**
