### PR TITLE
[WIP] Add a private rest API

### PR DESCRIPTION
**Pull request by quentinlesceller**
Fixes https://github.com/mimblewimble/grin/issues/1290.

Introduce another REST API with auth (`?secret=SECRET) in url listening by default on localhost:13412.
Private api calls are for now:
- Everything peers related
- Node status
- Pool info
- Chain compact/validate

Thoughts?

### CODE REVIEW

**Comment by ignopeverell** [comment]
Wouldn't HTTP Basic Auth be better? It's standard, your browser would do the right thing, it doesn't involve the server seeing your secret. It can be a little bit more complicated for clients, but a lot of libraries support it.

**Comment by kargakis** [comment]
Avoid using secrets in url parameters. Usually you do http auth via headers.

**Comment by quentinlesceller** [comment]
Closing that one in favor of a single protected API. I will link the new PR here.

**Comment by kargakis** [comment]
Replaced by https://github.com/mimblewimble/grin/pull/1566

**Pull request closed without merging**
