### PR TITLE
BIP32 Lib Integration

### PR DESCRIPTION
**Pull request by yeastplume**
First part of #1428, with this PR I just intend to

* Integrate @apoelstra's BIP-32 implementation into our code in the least impactful way possible
* Figure out what hashing we'll support and how. Most likely thinking for now I want to abstract the hashing into a trait and provide a Blake2 implementation of it, then import and have an implementation for the actual BIP-32 SHA/ripemd hashing just for test cases
* Get tests in place

The way this is getting integrated really making me think we need a better separation between wallet and server code, (for instance, I'd like to be able to import whatever hash libs into the wallet code without worrying about bloating grin) but we can handle that another day.

### CODE REVIEW

**Comment by mcdallas** [comment]
@yeastplume I already have done some work on this but it's nowhere near working state, I can push my branch if you want before you start working at this

**Comment by yeastplume** [comment]
@mcdallas Sorry didn't mean to invalidate what you're doing. Andrew's implementation is already there and been tested at least somewhere (and mostly uses the same libraries that we do), so it seems to make sense just to integrate that. All that really needs to be done is to swap out the hash functions, so this is just about there already.

Perhaps I can just finish integrating this bit so we have our working extended key in place and you can pick it up from there?

**Comment by mcdallas** [comment]
@yeastplume No problem at all. I was just trying to save you some work because you seem to be doing the same thing. I have already created two structs ExtendedPrivKey and ExtendedPubKey mostly based on andrew's code and swapped the hmac-sha512 with blake2. Code [here](https://github.com/mcdallas/grin/commit/27853582b3948f3d3adce5a5dfc8f0cc7efbd72a).

> Perhaps I can just finish integrating this bit so we have our working extended key in place and you can pick it up from there?

Whatever suits you is fine with me.

**Comment by yeastplume** [comment]
Thanks! No worries, should be in fairly shortly. Actually, I see what's gone on now, I think @ignopeverell or some early contributor took that code originally and cut it down for a simplified key derivation. Not sure why that might have been done (was before my time).

**Comment by yeastplume** [comment]
@antiochp @ignopeverell So we have the BIP32 module integrated there now, passing unit tests but otherwise not being used. I've factored out the actual hashing calls and some seeds into a trait, in case we wanted to replace any call with Blake2. (We'll certainly want to change a couple of seed values, I think).

This ends up re-introducing rust-crypto, but only for Sha/Ripemd hashing. I think we may be okay to stick with the BIP32 hash algos as much as possible; performance shouldn't be an issue since we should never need to grind through them on restore if we wind the key indices into an output's bullet proof as we've been talking about. Thoughts?

**Comment by apoelstra** [comment]
https://github.com/rust-bitcoin/bitcoin_hashes will eventually be a better choice than rust-crypto (no deps, supports specifically the Bitcoin hashes). But it has open PRs for SHA512 and HMAC so right now it can't be used for BIP32.

**Comment by ignopeverell** [comment]
My take: at this point, anything half decent would be a real improvement.

**Comment by yeastplume** [comment]
bitcoin_hashes looks like a great idea. I'll merge what's there for now (using rust-crypto) so we can move on, but looks like it should just be a drop in replacement once it's ready.

**Pull request merged**
