### PR TITLE
correct a mistake in intro

### PR DESCRIPTION
**Pull request by dumingxiao**
k1 is the private key. We should sign a transaction with the private key.

### CODE REVIEW

**Comment by garyyu** [comment]
Normally, when we say `sign sth with P`, if `P` here is a public key, we know what it means.
Does this indeed cause some people confusing?

**Comment by dumingxiao** [comment]
> Normally, when we say `sign sth with P`, if `P` here is a public key, we know what it means.
> Does this indeed cause some people confusing?
Sorry, did I misunderstand the description? Here you want to use a public key to sign as a new private key?

**Comment by dumingxiao** [comment]
> Normally, when we say `sign sth with P`, if `P` here is a public key, we know what it means.
> Does this indeed cause some people confusing?

Sorry, did I misunderstand the description? Here you want to use a public key to sign as a new private key?

**Comment by jaspervdm** [comment]
To verify the signature you only need `x*G` so I think its valid to see the signature as one for `x*G`. The phrases "sign with `x*G`" and "sign with `x`" usually mean the same thing and are used interchangably.

**Pull request closed without merging**
