### PR TITLE
Add a maximum size to stempool

### PR DESCRIPTION
**Pull request by quentinlesceller**
Fixes https://github.com/mimblewimble/grin/issues/1416. Introduce a `maximum_stempool_size`, same as `maximum_pool_size` by default.

### CODE REVIEW

**Comment by antiochp** [comment]
What happens if a node refuses to accept a stem tx? Does the originator get notified of this or is it silently dropped?

We want to make sure no info is "leaked" with this.

But if this is silently dropped - what happens to the stem tx itself? An upstream peer timer will expire and the tx gets broadcast?

Either way, practically speaking I'm not sure how big the stempool will ever get for a given size of network and tx volume  (I'm guessing its going to be pretty small...)

**Comment by quentinlesceller** [comment]
Normally, the plan is that the originator does not knows that the pool is full (need to check the code out that).
And yes if it gets silently dropped, the timer expires and the tx is fluffed.,

I'm currently working on removing transaction from the mempool instead of just giving an error. However, I'm not quite sure what we should do with the stempool. We cannot drop stem tx under embargo. I'm worried that someone could just spam a node with high fees stem tx and technically empty the stempool or whatever is the logic to do when stempool is full (but this is the same security trade off as all cryptocurrencies).

**Comment by antiochp** [comment]
:+1:

I think "spam a node with high fees stem tx" has to be treated as valid txs and not really spam (assuming they are valid txs)?

**Comment by quentinlesceller** [comment]
Indeed, but in that case should we evict from stempool or just silently drop the transaction (I'm leaning toward the latter)?

**Comment by antiochp** [comment]
Yeah I'm leaning toward that as well - keep it simple and just do "first in wins" and assume the timers on other stem nodes will handle it correctly.

**Comment by quentinlesceller** [comment]
Regardless of #1898. I think we can merge this one safely.

**Pull request merged**
