### PR TITLE
Replace RefCell with RwLock in OneTime (and cleanup Weak usage)

### PR DESCRIPTION
**Pull request by antiochp**
This builds and runs... why do we need the complexity of weak refs?

### CODE REVIEW

**Comment by hashmap** [comment]
Technicaly we create a memory leak, but if we have more or less static objects (fixed number, static lifetime) - I think adapters and peers/chain are such objects - we can live with that.

**Comment by antiochp** [comment]
That's kind of what I was thinking. We have one `peers` instance and one `chain` instance. They are basically singletons. We are never going to (at least in the current impl) swap them out at runtime for other instances etc.

**Comment by antiochp** [comment]
https://doc.rust-lang.org/std/sync/struct.Arc.html#thread-safety

> Arc<T> will implement Send and Sync as long as the T implements Send and Sync. Why can't you put a non-thread-safe type T in an Arc<T> to make it thread-safe? This may be a bit counter-intuitive at first: after all, isn't the point of Arc<T> thread safety? The key is this: Arc<T> makes it thread safe to have multiple ownership of the same data, but it doesn't add thread safety to its data. Consider Arc<RefCell<T>>. RefCell<T> isn't Sync, and if Arc<T> was always Send, Arc<RefCell<T>> would be as well. But then we'd have a problem: RefCell<T> is not thread safe; it keeps track of the borrowing count using non-atomic operations.

Big alarm going off from that last sentence - 

> RefCell<T> isn't Sync, and if Arc<T> was always Send, Arc<RefCell<T>> would be as well. But then we'd have a problem: RefCell<T> is not thread safe; it keeps track of the borrowing count using non-atomic operations.

@hashmap

**Comment by ignopeverell** [comment]
With 2 `Arc`s referencing each other you can never cleanly stop the server. The issue is described here:

https://doc.rust-lang.org/std/sync/struct.Arc.html#breaking-cycles-with-weak

Regarding `RefCell`, you may have found the cause of those `BorrowError`s. Indeed the borrowing counters aren't atomic. That being said we only borrow mutably once at startup, so that's still a tad weird. But perhaps still worth replacing with a `RwLock`.

**Comment by garyyu** [comment]
Thanks for digging into this, both @hashmap and me dug days with headache on this `Weak` in https://github.com/mimblewimble/grin/issues/1551.  Perhaps it's better to find another way out like you.

As Igno said, we have 2 Arc referencing each other (the root reason to use this `Weak`), Peers contains Adapter, and Adapter contains Peers:
```
pub struct Peers {
	pub adapter: Arc<ChainAdapter>,
	...
}
```

```
pub struct NetToChainAdapter {
	...
	peers: OneTime<Weak<p2p::Peers>>,
	...
}

pub struct ChainToPoolAndNetAdapter {
	...
	peers: OneTime<Weak<p2p::Peers>>,
}

pub struct PoolToNetAdapter {
	peers: OneTime<Weak<p2p::Peers>>,
}
```

As you (@antiochp ) said, we just use Peers as singleton (only ONE instance), why not split `peers` from Adapters and just use a util function to get it, instead of put `peers` as a field of Adapters structure.

**Comment by hashmap** [comment]
@antiochp really nice catch! It explains BorrowError, which happens when the counter is -1, which could happen with non-atomic updates. We could wrap RefCell into RwLock, wdyt? We still need interior mutability here.

**Comment by antiochp** [comment]
I think a RwLock gives us the interior mutability that we need no?

We take a write lock to initialize the OneTime.
Then read locks subsequently.

We should definitely not be using a RefCell across threads as it is explicitly marked as _not_ thread-safe.

**Comment by antiochp** [comment]
Hmm. Everything seems to be fine when running a node (it does appear to cleanly shutdown).

But we see this when running tests (`grin_servers`) on MacOS - 

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

TxHashSetErr: Too many open files (os error 24) })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
test simulate_seeding ... FAILED
```

Which I guess is related to the "leak" - we're not cleaning up the various grin servers in the tests while the tests are running.

Going to take another look at reintroducing the `Weak` refs now that we are using `RwLock` in `OneTime`.

**Comment by garyyu** [comment]
@antiochp  
> Too many open files ...
> Which I guess is related to the "leak"

This error on the test is because of OS file limitation, you need change default value by:
```
sudo ulimit -n 512
```
And check it before change it:
```
ulimit -n
```

**Comment by antiochp** [comment]
But why would it start happening all of a sudden?
My theory was this is related to "servers" in the tests not getting cleaned up due to refs hanging around? And these servers are keeping file handles open.

**Comment by garyyu** [comment]
Not only the **file** handler, I think most of them are sockets. On the server test, we open too many sockets. Perhaps need to check if they are closed quickly.

And I remember there's some tool to check the opened file handlers.

And did you upgrade your computer OS version recently?  it could change your default `ulimit -n`.

**Pull request merged**
