### PR TITLE
return the finalized slate from the post_tx endpoint

### PR DESCRIPTION
**Pull request by rentenmark**
* Includes a proper description of what problems the PR addresses, as well as a detailed explanation as to what it changes

The API for post_tx should return the finalized transaction slate for posterity.

* Explains whether/how the change is consensus breaking or breaks existing client functionality

This change may break some clients and would probably be best to wait for V2 but I wanted to put it here as a discussion point.  

* Contains unit tests exercising new/changed functionality

No unit tests for API at the moment

* Fully considers the potential impact of the change on other parts of the system

Only touching outer skin, really just integration points.

* Describes how you've tested the change (e.g. against Floonet, etc)

WIP 

* Updates any documentation that's affected by the PR

https://github.com/mimblewimble/grin/blob/master/doc/api/wallet_owner_api.md#post-post-tx

### CODE REVIEW

**Comment by garyyu** [comment]
`post_tx` return slate?!  but slate isn't the input of `post_tx`?

**Comment by rentenmark** [comment]
Yes, if I understand things correctly the `api.post_tx` function modifies the slate transforming it from `responseTx` state to `finalTx` state. This returns the slate in its "final form"

I could absolutely be completely wrong about this. That's just me reading into the method signature.

**Comment by jaspervdm** [comment]
Posting a transaction to the node doesn't change the slate in any way

**Comment by garyyu** [comment]
@rentenmark 
Another option is to use `repost-tx` API, which don't need the caller to provide the input slate:
https://github.com/mimblewimble/grin/blob/master/doc/api/wallet_owner_api.md#post-repost-tx

And let's close this PR :-) but pls feel free to find us on support channel to continue the discussion about this.

**Pull request closed without merging**
