### PR TITLE
[T4] change compaction check trigger to 1 day and cut_through_horizon to 1 week

### PR DESCRIPTION
**Pull request by garyyu**
This PR will close https://github.com/mimblewimble/grin/issues/1715
- compaction blocks change from 2000 to 10080, i.e. one week.
- use a `constants.rs` for constants, for the moment, only one is there. will move more to there when see them.

### CODE REVIEW

**Comment by garyyu** [comment]
Remind myself about how the `compact()` is using this `cut_through_horizon`:
```
	pub fn compact(&self) -> Result<(), Error> {
		...
		let horizon = global::cut_through_horizon() as u64;
		...
		let mut current = batch.get_header_by_height(head.height - horizon - 1)?;
		loop {
			match self.store.get_block(&current.hash()) {
					...
					batch.delete_block(&b.hash())?;
			...
			match batch.get_block_header(&current.previous) {
		...
		}
```

**Comment by antiochp** [comment]
I think that's right yes - that way we get regular compaction steps happening, but we have a reasonably large history to work with to handle forks.

We should check if anyone has concerns with these numbers though.

**Comment by garyyu** [comment]
Updated. And request @ignopeverell  to take a look.

**Comment by antiochp** [comment]
Something to think about - 

Do we introduce problems network wide if _all_ nodes trigger compaction at exactly the same height?
Basically every 1440 blocks (i.e. at height 1440, 2880, 4320 etc.) all nodes run compaction.
We basically have a big (relatively speaking) "garbage collection" pause at these heights.

To be good citizens all nodes should maintain at least 10080 historical blocks, but _when_ compaction runs can be more flexible and potentially randomized?

**Comment by garyyu** [comment]
Good point 👍 
So, let's change to:
```
if tip.height % global::COMPACTION_CHECK == get_ip_addr() % global::COMPACTION_CHECK
```

**Comment by antiochp** [comment]
I was actually thinking simpler than that - 

Why do we not just "roll a die" every block and set it up so on average we run compaction once per day?
Which is roughly 0.07% chance per block (better check my math though).
Then we can replace the trigger value with a percentage value (and this _can_ be configurable per node). 

This would be similar to what we do for Dandelion stem vs fluff (where we fluff a tx 10% of the time).

**Comment by garyyu** [comment]
Roll the dice:
```
let mut rng = thread_rng();
if 0 == rng.gen_range(0, global::COMPACTION_CHECK) {
    ...
}
```

Is happy now? 😄

**Comment by garyyu** [comment]
Sorry, I just submit the modification 😄  now the discussed solution code is ready in PR.

**Pull request merged**
