### PR TITLE
Update Client to v2 API

### LINKED ISSUE #3522: Client use v1 API
The current `grin client` uses the V1 API which is now removed.
Convert it to v2. https://github.com/mimblewimble/grin/blob/v5.0.0-beta.2/src/bin/cmd/client.rs#L159v

### PR DESCRIPTION
**Pull request by quentinlesceller**
As titled. Fixes #3522.
JSON-RPC code is taken from https://github.com/mimblewimble/grin-wallet/pull/329 (json-rpc.rs). Might be good to use the same code for both in the future.

### CODE REVIEW

**Comment by antiochp** [comment]
Looks like there are build issues related to the `json!` macro.

**Review by jaspervdm — APPROVED** [review]
👍 Tested locally and behaves as expected.

**Review by antiochp — COMMENTED** [review]
Changes look fine.
I'm testing this locally just to sanity check the various `client` api calls.

**Review by antiochp — APPROVED** [review]
:+1:

**Comment by antiochp** [comment]
Merging this. My understanding is this is the last PR outstanding for `5.0.x`.

**Pull request merged**
