### PR TITLE
First draft of specs for wallet security considerations and apis

### PR DESCRIPTION
**Pull request by camalolo**

### CODE REVIEW

**Comment by sesam** [comment]
@camalolo we'll probably merge this soon. Any objections?

**Comment by camalolo** [comment]
No objection from me, the document will still need input from the community, cheers !

**Comment by knarz** [comment]
Seeing as this is about "security considerations", having a clearly stated threat model might be helpful.

**Comment by yeastplume** [comment]
Think this has gone a bit stale and out of date, so will close for now.

**Pull request closed without merging**
