### PR TITLE
[DOC]translate documents & fix some typo

### PR DESCRIPTION
**Pull request by MegaSolar**
- **doc/coinbase_maturity** translated in Korean .
and fixed some typo to understand easily. 

Feedbacks would be welcomed.

### CODE REVIEW

**Comment by ignopeverell** [comment]
Looks like ` doc/internal/pool_KR.md` is all English?

**Comment by MegaSolar** [comment]
@ignopeverell oops my bad. 
I erased it. 

thank you :)

**Comment by MegaSolar** [comment]
@ignopeverell ping.

**Comment by quentinlesceller** [comment]
Closed for https://github.com/mimblewimble/grin/pull/2952.

**Pull request closed without merging**
