### PR TITLE
minimal stratum server

### PR DESCRIPTION
**Pull request by bladedoyle**
Originally implemented on testnet1 source:  https://github.com/mimblewimble/grin/pull/779

For support of mining pools and remote miners: https://github.com/mimblewimble/grin/issues/935

Merged with testnet2

### CODE REVIEW

**Comment by bladedoyle** [comment]
Continued from testnet1 branch: https://github.com/mimblewimble/grin/pull/779

**Comment by bladedoyle** [comment]
Sure, give me a few days to refactor mining and stratum code into a "miner" create one level up.  

Im eager to get these changes merged so I would prefer to handle miner decoupling, etc.. as a spearate pull request.

**Comment by yeastplume** [comment]
Yep the miner decoupling will evolve over time, and I can do some work on it as well.

**Comment by bladedoyle** [comment]
@yeastplume @ignopeverell 
Can you provide some guidance on how to deal with the "adaptors.rs" module currently in grin_grin.  Parts of adaptors.rs is needed by the new "miner" crate and also in "servers.rs".  Maybe I need to move it up a level so it can be used by both without creating a circular dependency?  It does not seem to fit into any existing crate (does it?), so maybe it needs to be a crate by itself?

Ref:  
* https://github.com/bladedoyle/grin/blob/7c3e0359e30bd729471ba6677b4391402261d59d/grin/src/stratumserver.rs#L200
* https://github.com/bladedoyle/grin/blob/7c3e0359e30bd729471ba6677b4391402261d59d/grin/src/server.rs#L52

**Comment by sesam** [comment]
@bladedoyle realistically the options are
1. new crate
2. squeeze into existing crate which might get messy
3. (unless I've misundersttod things here) allow circular crate deps (I think we have some already) and use weak references that get upgraded on use, see macros.rs `wo` and `w`

**Comment by yeastplume** [comment]
Let me try and refactor a bit.. I think the best thing to do might be to rename the `grin` crate to `servers`, and have the individual servers in their own subdirectories

**Comment by yeastplume** [comment]
See https://github.com/mimblewimble/grin/pull/955.. if everyone else is okay with the approach there then we'll have a logical place to put the stratum miner.

**Comment by yeastplume** [comment]
Okay, though the merge history has got a bit mangled, I think the merge should be fine so I'll go ahead and merge so we can move on to the next phases

**Pull request merged**
