### PR TITLE
Fix ROARING_ARCH environment variable

### LINKED ISSUE #3641: Grin node 5.1.0 won't launch on Linux
**Describe the bug**
Grin node v5.1.0 will not launch on Debian Buster, returning "Illegal instruction" to stdout.

**To Reproduce**
```
$ grin
Illegal instruction
$ echo $?
132
$ ps aux |grep -E '[g]rin'
$ 
```

**Relevant Information**
```
20210506 16:53:04.446 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug                                                                                      
20210506 16:53:04.447 INFO grin - Using configuration file at /home/$USER/.grin/main/grin-server.toml
20210506 16:53:04.447 INFO grin - This is Grin version 5.1.0 (git v5.1.0), built for x86_64-unknown-linux-gnu by rustc 1.51.0 (2fd73fabe 2021-03-23).                                                               
20210506 16:53:04.448 DEBUG grin - Built with profile "release", features "".
20210506 16:53:04.448 INFO grin - Chain: Mainnet
20210506 16:53:04.448 INFO grin - Accept Fee Base: 500000
20210506 16:53:04.449 INFO grin - Future Time Limit: 300
20210506 16:53:04.449 INFO grin - Feature: NRD kernel enabled: false
20210506 16:53:04.449 WARN grin::cmd::server - Starting GRIN in UI mode...
20210506 16:53:04.450 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20210506 16:53:04.451 DEBUG grin_store::lmdb - DB Mapsize for /home/$USER/.grin/main/chain_data/lmdb is 549755813888
```

**Desktop (please complete the following information):**
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### PR DESCRIPTION
**Pull request by quentinlesceller**
Good catch @antiochp :). Fixes #3641.

### CODE REVIEW

**Comment by GeneFerneau** [comment]
Does there also need to be an environment variable to disable croaring on some arches as suggested [here](https://github.com/mimblewimble/grin/issues/3641#issuecomment-845369915) and [here](https://github.com/mimblewimble/grin/issues/3641#issuecomment-845384714)?

**Comment by quentinlesceller** [comment]
My understanding is that with the x86-64-v2 arch, croaring will not use AVX and as such is compatible with all archs. Or did I miss something?

**Comment by GeneFerneau** [comment]
I just wasn't sure, saw mention of the disable env var, didn't know if it was necessary for some builds.

**Review by GeneFerneau — APPROVED** [review]

**Comment by phyro** [comment]
Should we go ahead and merge this one and prepare a new minor release? Then perhaps people at https://github.com/mimblewimble/grin/issues/3641 can give it a try

**Comment by quentinlesceller** [comment]
Merged! Unsure if we need a minor release for that though.

**Pull request merged**
