### PR TITLE
move verify_kernel_sums into committed trait

### PR DESCRIPTION
**Pull request by antiochp**
* move `Committed` trait out into `committed.rs`
* add `verify_kernel_sums()` to committed trait
* add `overage()` and `total_overage()` to block header for convenience
* rework block, transaction and txhashset validation to all use `verify_kernel_sums()` from trait (they were all using their own slightly different variations of the same code)

### CODE REVIEW

**Comment by antiochp** [comment]
No behavior changes with this - its just moving code around.
Makes transaction, blocks and txhashsets even closer now in terms of validation.

Merging.

**Comment by kargakis** [comment]
Are kernels and kernel offsets documented anywhere?

**Comment by antiochp** [comment]
Kernels yes - https://github.com/mimblewimble/grin/blob/master/doc/intro.md
Kernel offsets - I don't think so. Maybe I'll put something together over the next few days.

**Comment by kargakis** [comment]
@antiochp thanks - I opened https://github.com/mimblewimble/grin/issues/1135 to track

**Pull request merged**
