### PR TITLE
[Done][doc] Chinese Translation

### PR DESCRIPTION
**Pull request by Funkyswing**
name: Chinese translation of files in doc
about: The files are going to translate:
- [x] [coinbase_maturity_ZH-CN.md](https://github.com/Funkyswing/grin/blob/master/doc/coinbase_maturity_ZH-CN.md)
- [x] [contracts_ZH-CN.md](https://github.com/Funkyswing/grin/blob/master/doc/contracts_ZH-CN.md)
- [x] [stratum_ZH-CN.md](https://github.com/Funkyswing/grin/blob/master/doc/stratum_ZH-CN.md)
- [x] [switch_commitment_ZH-CN.md](https://github.com/Funkyswing/grin/blob/master/doc/switch_commitment_ZH-CN.md)
- [x] [table_of_contents-ZH-CN.md](https://github.com/Funkyswing/grin/blob/master/doc/table_of_contents_ZH-CN.md)

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Hi @Funkyswing. Are you going to translate the document above?  Please note that there is a conflicting file too. Thanks :)

**Comment by Funkyswing** [comment]
> 
> 
> Hi @Funkyswing. Are you going to translate the document above? Please note that there is a conflicting file too. Thanks :)

Hi @quentinlesceller , I just got the confilct in the file 'grin4bitcoiners_ZH-CN' resolved. If any more questions, just let me know. :)

Thanks.

**Comment by Funkyswing** [comment]
@quentinlesceller 
Hi, you could merge this five documents. 

Thanks.

**Comment by Funkyswing** [comment]
@quentinlesceller 
Could you cimmit this please?
Thanks.

**Comment by quentinlesceller** [comment]
Awesome. Thanks for the translation @Funkyswing. Quite significant work!

**Pull request merged**
