### PR TITLE
minor improvement on stratum server log for miner status

### PR DESCRIPTION
**Pull request by garyyu**
In case of TUI off on server, it's not easy to read the miner worker status. So, I add this one line of log to show almost same thing as the status showed in TUI:
```
20190106 23:55:54.007 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 102, Rejected: 0, Stale: 0. Blocks Found: 0/0
20190106 23:56:25.004 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 114, Rejected: 0, Stale: 0. Blocks Found: 0/0
20190106 23:56:56.018 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 141, Rejected: 0, Stale: 0. Blocks Found: 0/1
20190106 23:57:26.971 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 168, Rejected: 0, Stale: 0. Blocks Found: 0/1
20190106 23:57:57.983 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 187, Rejected: 0, Stale: 0. Blocks Found: 0/1
20190106 23:58:28.993 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 208, Rejected: 0, Stale: 0. Blocks Found: 0/1
20190106 23:58:59.973 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 232, Rejected: 0, Stale: 0. Blocks Found: 0/1
20190106 23:59:30.972 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 250, Rejected: 0, Stale: 0. Blocks Found: 0/3
20190107 00:00:02.014 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 273, Rejected: 0, Stale: 0. Blocks Found: 0/3
20190107 00:00:32.984 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 293, Rejected: 0, Stale: 0. Blocks Found: 0/3
20190107 00:01:03.992 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 313, Rejected: 0, Stale: 0. Blocks Found: 0/4
20190107 00:01:34.968 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 335, Rejected: 0, Stale: 0. Blocks Found: 1/6
20190107 00:02:05.986 DEBUG grin_servers::mining::stratumserver - (Server ID: 0) Status of worker: 0 - Share Accepted: 356, Rejected: 0, Stale: 0. Blocks Found: 1/6
```

### CODE REVIEW

**Comment by garyyu** [comment]
@ignopeverell , no, it can't break, because I just log, no change on the message.

**Comment by hashmap** [comment]
@garyyu it may, shares accounting is built on top of log parsing

**Comment by bladedoyle** [comment]
Thanks @garyyu  and @ignopeverell I appreciate the heads-up.  I have not yet moved away from message parsing, but this isnt one of the messages I use so it will not impact me.

**Comment by garyyu** [comment]
OK, thanks for your review~   then I go to merging now :)

**Pull request merged**
