### PR TITLE
[WIP] Intoduce fuzz tests

### PR DESCRIPTION
**Pull request by hashmap**
This PR introduces fuzz tests and address #592, initial version contains just one for
reading transaction. It also includes some fixes to make this test pass.
Without it the code panics in 2 different places. Inroduced limits are basically
placeholders, should be replaced with more usable values.

Cargo-fuzz (https://github.com/rust-fuzz/cargo-fuzz) has been used. To install
`cargo install cargo-fuzz`.  To run the test cd
to `core` folder and run `cargo fuzz run transaction_read`.

[https://github.com/mimblewimble/grin/issues/592]

### CODE REVIEW

**Comment by ignopeverell** [comment]
This is pretty awesome, great that it already found some weaknesses in deserialization. Is there a way to add fuzz tests to our standard test suite?

**Comment by hashmap** [comment]
Not sure, it takes a lot of time. I'll try to provide libfuzz with samples (e.g. a valid txs), it may speed it up.

**Comment by ignopeverell** [comment]
Ok, let's see, Travis is already not too happy about us because of tests time.

**Comment by ignopeverell** [comment]
Checked your changeset, you meant the path in the Merkle proof. 100 should be more than enough, no one would have enough available memory to hold a 2^100 sized tree.

**Comment by ignopeverell** [comment]
Fuzz tests have led to good fixes. Is this still WIP? Maybe fix conflicts and we can merge this, and have further improvements as another PR?

**Comment by hashmap** [comment]
I did a few merges, so now it's hard to squash commits. I'm closing this pr and will open a new one with clean history of commits

**Pull request closed without merging**
