### PR TITLE
updates to mining stats tui

### PR DESCRIPTION
**Pull request by bladedoyle**
add column ordering and set mining workers table to sort the connected workers to the top by default

### CODE REVIEW

**Comment by antiochp** [comment]
@bladedoyle we had some issues with CI windows builds. Want to rebase or merge master into this PR and get it kick another CI build off?

**Comment by bladedoyle** [comment]
@antiochp   Thanks for the heads-up.   I made an attempt at merge with master

**Comment by antiochp** [comment]
@bladedoyle @quentinlesceller Are we considering including this in `5.0.x`?

**Comment by bladedoyle** [comment]
> @bladedoyle @quentinlesceller Are we considering including this in `5.0.x`?

Yes please.

**Comment by bladedoyle** [comment]
Closed due to lack of interest.

**Pull request closed without merging**
