### PR TITLE
initial docs and images to describe receiving a block and simple sync.

### PR DESCRIPTION
**Pull request by antiochp**

### CODE REVIEW

**Comment by antiochp** [comment]
Oof. Might need to re-export these images as pngs... (was hoping this would work as svgs).

**Comment by ignopeverell** [comment]
This is great. We can also add #403 once we start on it.

**Comment by antiochp** [comment]
I want to keep referring back to this as we cover more scenarios - so none of us goes down a path of assuming a head points at one place when it actually does something else (and maybe helps us track down weird behavior when its not doing what we expect).

**Comment by kargakis** [comment]
Should this doc be collapsed into https://github.com/mimblewimble/grin/blob/master/doc/chainsync.md or at least grouped under the same dir?

**Comment by antiochp** [comment]
Yeah quite likely. Still iterating on this.

**Pull request merged**
