### PR TITLE
small correction for H

### PR DESCRIPTION
**Pull request by fixone**
change H from 'elliptic curve' to 'generator of an elliptic curve'

### CODE REVIEW

**Comment by ignopeverell** [comment]
I've been hesitant about those changes (you're not the first to try to make the terminology more accurate). The guide is aimed at people with little ECC knowledge and I think it does a pretty good at that. If you know what a generator point is, you'll get what all of this is anyway.

**Comment by sesam** [comment]
:+1: on keeping it easy to grasp for newcomers.

How about instead adding a link like "[More details](https://github.com/mimblewimble/docs/wiki/Jargon-file-and-glossary#elliptic-algebra)
and there we can define (and also further teach newcomers) on the meaning of the different symbols commonly used.

**Comment by fixone** [comment]
I'm for simplicity, but also for consistency. Note how a bit further down it says "(practically G is just another generator point on the same curve group as H)". So it already makes it clear that H is not a curve but a point on it

**Comment by sesam** [comment]
good catch.
So the options are: 
curve (group) / generator (point)
The simplest is maybe to change to curve throughout the text, then explain the details and G vs H relation either at the end of the document, or the wiki.

cc @ignopeverell et al

**Comment by ignopeverell** [comment]
How about moving and adapting the clarification between parentheses to that first occurrence of the "elliptic curve" simplification.

**Pull request closed without merging**
