### PR TITLE
Fix fraud peer detection, introduce more agressive ban

### PR DESCRIPTION
**Pull request by hashmap**
Currently we ban a current syncing peer if we didn't get headers in 120s, however we send a new headers request every 10s and select a new syncing peer. That last peer is no more guilty than previous ones. Moreover, this situation is very unlikely and happens when we have some network issue on our side.

Usually we have one unresponsive peer which we never ban, so we just spent more time on syncing. NAT'd peer has up to 8 peers, so keeping one unresponsive peer affects header sync's performance sufficiently.

This PR removes 120s grace period and bans unresponsive peers after 10s timeout. I made a few full syncs and found that my node bans the same 3 peers, so this approach seems to be working well.

### CODE REVIEW

**Comment by antiochp** [comment]
Related - https://github.com/mimblewimble/grin/issues/3292

**Comment by antiochp** [comment]
> Currently we ban a current syncing peer if we didn't get headers in 120s, however we send a new headers request every 10s and select a new syncing peer. That last peer is no more guilty than previous ones.

Oh is that what is happening here? We randomly choose a new peer every 10s and then eventually ban an arbitrary peer based on it being unlucky at the 120s threshold?

I'm guessing the intent was to eventually the ban the one non-responsive peer but now I'm not even sure this was fully thought through...

I need to go over the code again but yeah I think this potentially makes sense to simplify like this.

**Comment by DavidBurkett** [comment]
> I'm guessing the intent was to eventually the ban the one non-responsive peer but now I'm not even sure this was fully thought through...

@garyyu wrote this IIRC, so he could provide more insight if he has anything to add. The original intention though was to just prevent peers from advertising a height they didn't have a block for, and therefore forcing nodes into header sync mode from which they never recover.

Igno always strongly cautioned against banning slow peers, which is probably why the original code didn't just ban everytime the peer failed to provide a requested header right away. I believe his concerns have been shown to be unwarranted, since the network has done fine for slower peers despite grin++'s ruthless banning policies.

**Comment by antiochp** [comment]
Dropped the ball on getting this in for 4.0.0.
Lets pick this up again once we get through HF3 and get this merged.

**Comment by bladedoyle** [comment]
I tested this change with a "slow disk" node (see https://github.com/mimblewimble/grin/issues/3561#issuecomment-779413163)

The issue of banning (healthy) peers at random is not improved. 
It seems like incorrect logic to ban a specific peer (whichever peer happens to be currently selected as syncing_peer) based on the global sync state.
Also, hardcoded 10 seconds may not be good for all situations.....it seems very short for nodes running on slow systems.

**Comment by antiochp** [comment]
@bladedoyle thanks for testing this out locally with a slow disk. :+1:

**Comment by yeastplume** [comment]
Closed and marked as 'abandoned'. This does not mean the PR is unworthy. This means that merging it would require further work that nobody appears prepared to do at this time, or the original author has been unresponsive for a significant amount of time. Anyone who want to continue work on this functionality is free to re-open this at any time.

**Pull request closed without merging**
