### PR TITLE
refactor(ci): reorganize CI related code

### PR DESCRIPTION
**Pull request by mrekucci**
Break-down the CI related code into smaller more maintainable pieces.

### CODE REVIEW

**Comment by yeastplume** [comment]
Thanks for looking into this, it certainly looks a lot cleaner. Just a few notes:

* This is one of those things that's fiddly to get working in the first place, so just wondering if you've tested all the build/test permutations against your repository?
* Windows targets were added into the 1.1.0 branch, so these would also need to be included
* Both `grin-wallet` and `grin-miner` repositories use scripts derived from the build scripts in grin, so ideally these would all need to be ported to the refactored format as well.

**Comment by garyyu** [comment]
thanks @mrekucci ! indeed much cleaner 👍 
Let me do some test on my repo, and I will work together for a bit further enhancement on this 😄  also for @yeastplume 's comments.

**Comment by mrekucci** [comment]
@yeastplume thanks for your comments. I tested this on my own Grin forked repo except for the changelog patch in the `release` script since I don't have the auth token from the Grin repo. I'll add the Windows targets from `1.1.0` branch. As soon as the PR will be merged I can change the scripts in `grin-wallet` and `grin-miner` @garyyu would be great if you could test the last mile thanks :)

**Comment by yeastplume** [comment]
Thanks, great to hear

Just thought I’d add a reference to https://github.com/mimblewimble/grin/pull/2626, there are still a few funnies related to windows builds on travis CI that I’ve outlined there to prevent others losing time on them

**Comment by mrekucci** [comment]
Windows targets added.

**Comment by ignopeverell** [comment]
@yeastplume @garyyu okay with the PR in its current state?

**Comment by garyyu** [comment]
The release note doesn't work, I'm looking into it.

**Comment by garyyu** [comment]
Let's merge this so I can the nightly part :-)

**Pull request merged**
