### PR TITLE
Add unit tests for API Endpoint

### PR DESCRIPTION
**Pull request by quentinlesceller**
Fixes https://github.com/mimblewimble/grin/issues/434
Adds unit tests for the API Endpoint.
For now, mine a simple chain with a wallet and test each handler.

- [x] Test blocks handler
- [x] Test status handler
- [x]  Test peers handlers (including ban/unban) 
- [x] Test sumtree handler
- [x] Test chain utxo handler

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Update:
Trying to create a pool of 2 servers similarly to "simulate_seeding" in ```grin/tests/simultnet.rs``` in order to test the P2P handler.
 However, I noticed that in the simulate seeding test, after getting connected to each others the servers disconnected themselves with a connection error ```Client 127.0.0.1:31020 connection lost: Connection(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("early eof") }) })```.
After discussion with @yeastplume on Gitter looks like there is probably an issue here. 
I will try to fix it before finishing this PR.

**Comment by yeastplume** [comment]
Hi @quentinlesceller,

Just before you go too much further here, we couldn't merge this as is because of the duplicated code copied out of the grin/grin testing directory. 

Since these are integration tests that require a running server to test, they could probably just as easily go into grin/grin (where the rest of the integration tests are) for the time being rather then putting them in grin/api and having to refactor the testing framework out elsewhere. If you look in grin/tests for example I've put a wallet.rs file to test the wallet against a running server.. you can probably create an api.rs file alongside it and place tests there

**Comment by quentinlesceller** [comment]
Okay no problem will do.

**Comment by antiochp** [comment]
Looks good!

**Pull request merged**
