### PR TITLE
[DNM] clean-up the txhashset zip file and temp folder

### PR DESCRIPTION
**Pull request by garyyu**
My `floo/chain_data` folder becomes more and more bigger, 4.6G for 6 days:
```
$ du -s chain_data
4601608	chain_data

$ ls -l chain_data | grep txhashset
drwxrwxr-x 5 garyyu garyyu     4096 Dec 30 03:02 txhashset
-rw-r--r-- 1 garyyu garyyu 39838686 Jan  7 23:57 txhashset_snapshot_102503.zip
-rw-r--r-- 1 garyyu garyyu 45923180 Jan  9 18:23 txhashset_snapshot_14035.zip
...
-rw-r--r-- 1 garyyu garyyu 41937198 Jan  8 14:22 txhashset_snapshot_988669.zip
drwxr-xr-x 5 garyyu garyyu     4096 Jan  7 23:57 txhashset_zip_102503
drwxr-xr-x 5 garyyu garyyu     4096 Jan  9 18:23 txhashset_zip_14035
...
drwxr-xr-x 5 garyyu garyyu     4096 Jan  8 14:22 txhashset_zip_988669
```
There are a lot of temporary files there! Let's clean-up these garbage.

### CODE REVIEW

**Comment by garyyu** [comment]
**Update:**
Added a new commit to clean-up the remaining (last 30 minutes) txhashset zip files when grin exit, tested on Floonet and it works.

Ready for review if anyone want to take a look.

**Comment by garyyu** [comment]
@ignopeverell I propose we merge it before mainnet release. Because of:

- The 1st version of the mainnet release will be the most spreaded binary, and many nodes will stay in this 1st version for a longer time than 8 weeks, before they upgrade for any possible critical fix.

- This improvement will avoid a wrong reputation spreading that Grin `chain_data` folder will increase 5GB / Week, but people don't know there are plenty of garbage temp files there, and it's dangerous to manually delete files in `chain_data` folder. Grin is lightweight.

- This PR only impact the state syncing feature, and state syncing is easy to test. I already did those tests multiple times, both in sender side and in receiver side, including the grin server restart.

Anyway, it's just my proposal, please feel free to wait till post-mainnet :-) no pressure pls 😄

**Comment by ignopeverell** [comment]
Paging @antiochp and @yeastplume to see what they think. My feeling is that we can easily tell people to upgrade if they start complaining. Would actually be a good incentive to do so. But I can definitely understand your argument as well @garyyu.

**Comment by antiochp** [comment]
Related - #2311.

**Comment by garyyu** [comment]
@antiochp thanks for your review~

Looks like we can't catch the mainnet release if now switching to your perfect solution: clean-up based on cut-off instead of on a rough time.

Shall we merge this PR with this rough time solution for mainnet?  to avoid awkward situation for huge garbage files resides in chain_data folder. And once a new perfect solution is implemented, we just revert this PR and apply the new one, in the latter version.

**Comment by antiochp** [comment]
I vote for waiting until after mainnet is live to push a fix for this.

**Comment by ignopeverell** [comment]
As stated before, I'm leaning toward waiting after mainnet as well. It'd be a great reason for people to want to update.

**Comment by garyyu** [comment]
Alright, I will write another PR to fix this after mainnet.  And we can keep this PR here in case anyone want it before the new fix ready, they can pull it by themselves :-)

I will tag this as [DNM].

**Comment by ignopeverell** [comment]
Re-targeted this against `1.1.0`. Did it need anything more (I see it still has a [DNM] prefix)?

**Comment by garyyu** [comment]
@ignopeverell  sorry for delay, I will write another PR with @antiochp proposed solution, in this week.

**Comment by ignopeverell** [comment]
Replaced by #2569

**Pull request closed without merging**
