### PR TITLE
TUI mining server status: add blocks found statistics

### PR DESCRIPTION
**Pull request by garyyu**
Add statistics of mining worker's found solutions, and show this found solutions number in TUI:

screen shot 2018-12-14 at 1 38 34 pm

### CODE REVIEW

**Comment by garyyu** [comment]
Merging if nobody has concern 😄   and I do want this little improvement~

**Comment by jaspervdm** [comment]
What is "solutions found"? Is it number of graphs solved or number of 42-cycles found? If the latter, isn't it always equal to sum accepted+rejected+stale?

**Comment by garyyu** [comment]
@jaspervdm   it's `Solution Found for block {} - Yay!!!`  😄  not the `shares`.

**Comment by jaspervdm** [comment]
Ah, so maybe we should rename it to `blocks found`?

**Comment by garyyu** [comment]
OK:)  as you want~  will change it tomorrow morning.

**Pull request merged**
