### PR TITLE
get `/v1/blocks` without merkle_proof

### PR DESCRIPTION
**Pull request by invis87**
add flag 'no_merkle_proof' to `/v1/blocks` api to get blocks without checking merkle proof

### CODE REVIEW

**Comment by hashmap** [comment]
Thanks for the contribution! LGTM, would you mind to add a test to https://github.com/mimblewimble/grin-wallet/blob/master/integration/tests/simulnet.rs I know it seems strange, but we moved integration tests to the wallet repo.

**Comment by invis87** [comment]
@hashmap Yep, ofc, I didn't find tests on `grin` project thats why my PR without tests. But now I know where are they hide :)

**Comment by hashmap** [comment]
@invis87 yeah, this is confusing and less safe, I think we should bring node-specific tests back

**Comment by invis87** [comment]
@hashmap sorry for stupid question, but how can I run integration tests in `grin_wallet`:
1. run it
2. run on top of my changes on `grin`

I found that integration tests are disabled in `grin_wallet` :(

But of course I can add tests to `"http://{}:{}/v1/blocks/{}?no_merkle_proof"` in the same manner as it is done for `"http://{}:{}/v1/blocks/{}?compact"`. If I do so - should it be different PR or... How to do it right :) ?

**Comment by hashmap** [comment]
There is no such thing as a stupid question. We discussed this situation during this week’s dev meeting and decided to move node-related tests back to grin repo. I’d recommend to create an issue to implement this test, we can do it after moving the tests. I’ll test your code manually meanwhile, thanks!

**Comment by invis87** [comment]
@hashmap can you close https://github.com/mimblewimble/grin/issues/1477 please?

**Pull request merged**
