### PR TITLE
Change log level for found cuckoo solution event

### PR DESCRIPTION
**Pull request by hashmap**
Trace seems to be to low, there is a  user request to make it more visible
https://gitter.im/grin_community/Lobby?at=5aba24967c3a01610d7c211f

### CODE REVIEW

**Comment by yeastplume** [comment]
Definitely don't think this is info level worthy, though I can live with putting this at debug level for now.

**Comment by hashmap** [comment]
Oops, I wanted debug level as was suggested in gitter, my fault, fixing

**Comment by sesam** [comment]
See also https://github.com/yourowncrypto/grin/blame/b7bc8f41e19b92381fbb9972d316758c894596c3/grin/src/miner.rs#L564

that's an info! saying valid PoW found, and on which block it was applied. The trace! line getting changed here is maybe earlier in the process, and so with some more chance of being lost. Seeing a "sucessful block mined" type of message, only to loose it again, might be suboptimal.

**Comment by hashmap** [comment]
Yeah, in fact I stumbled upon this line before making change, probably it's why i typed `info` instead of  `debug`.

**Comment by sesam** [comment]
If you have time, maybe you can figure out some way to make this even clearer. If people are primarily wishing for a way to notice when they get some grins (so they can celebrate :tada:), one idea is to also adjust the other info! output to make is maximally userfriendly, and maybe add a link to, say, "https://grinexplorer.net/block/" + b.hash()

**Pull request merged**
