### PR TITLE
[WIP] docs: french translation

### PR DESCRIPTION
**Pull request by Th0rgal**
---
name: Pull request for french translation of the documentations
about: Translating the documentation in french
title: ''French translation"
labels: "translation"

---

Hello, everybody! I discovered the Grin project and MimbleWimble protocol recently. Both seem very interesting but I have to say that a large portion of it still looks like black magic to me, so I decided to go deeper into the subject starting by reading the documentation. Since I'm French I thought it might be a good idea to translate it to make sure I understand it, and may be it could help someone. For the moment I've started the introduction (there's a lot of work), feel free to tell me what you think!

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Hi @Th0rgal despite us having docs.grin.mw it could still be nice to have a translation. Are you still working on this ?

**Comment by Th0rgal** [comment]
> Hi @Th0rgal despite us having docs.grin.mw it could still be nice to have a translation. Are you still working on this ?

Hello @quentinlesceller ! I've been really busy these days but yeah I still think this would be a good idea and I'll try to improve it. I'll try to finish the first page soon. Do you want to contribute too?

**Comment by bentaye** [comment]
Hi @quentinlesceller, @Th0rgal, 
I'm happy to help if we still need that translation. French native here.

**Comment by quentinlesceller** [comment]
Indeed, this should be in the docs repo now. Especially since mkdocs-material support a language selector.

**Pull request closed without merging**
