### PR TITLE
batch verify proofs during validation

### PR DESCRIPTION
**Pull request by yeastplume**
For https://github.com/mimblewimble/grin/issues/1408

### CODE REVIEW

**Comment by garyyu** [comment]
Kindly remind:   for less than 105 proofs, batch verification is slower than single. 

So better to give different processing, for example:
```
if .len() < 105
    single verify
else
    batch verify
end
```

**Comment by yeastplume** [comment]
Doesn't seem to be the case. I've put a benchmark test into rust-libsecp256k here:

https://github.com/mimblewimble/rust-secp256k1-zkp/blob/0ec6b1d1bed02c224a39bf50a3f5397e3fae9084/src/pedersen.rs#L1138

Results from running this test locally are:

```
running 1 test
--------
Comparing 1 Proofs
1 proofs single validated in 3.313863ms
1 proofs batch validated in 3.251948ms
--------
Comparing 2 Proofs
2 proofs single validated in 6.5045589999999995ms
2 proofs batch validated in 3.776766ms
--------
Comparing 5 Proofs
5 proofs single validated in 15.909419999999999ms
5 proofs batch validated in 5.284765999999999ms
--------
Comparing 10 Proofs
10 proofs single validated in 32.122524999999996ms
10 proofs batch validated in 7.951619ms
--------
Comparing 100 Proofs
100 proofs single validated in 321.93348599999996ms
100 proofs batch validated in 50.316016999999995ms
--------
Comparing 200 Proofs
200 proofs single validated in 716.873334ms
200 proofs batch validated in 95.480992ms
```

Perhaps you can try that test on your local machine and see if you get the same result?

**Comment by garyyu** [comment]
With your test code, my result show same result as yours. Please let me check my original test and find out what happened.

```
running 1 test
--------
Comparing 1 Proofs
1 proofs single validated in 6.648ms
1 proofs batch validated in 6.749ms
--------
Comparing 2 Proofs
2 proofs single validated in 12.623999999999999ms
2 proofs batch validated in 7.159ms
--------
Comparing 5 Proofs
5 proofs single validated in 31.892999999999997ms
5 proofs batch validated in 11.164ms
--------
Comparing 10 Proofs
10 proofs single validated in 88.304ms
10 proofs batch validated in 15.572999999999999ms
--------
Comparing 100 Proofs
100 proofs single validated in 638.836ms
100 proofs batch validated in 90.87899999999999ms
--------
Comparing 200 Proofs
200 proofs single validated in 1281.373ms
200 proofs batch validated in 172.11599999999999ms
test pedersen::tests::bench_bullet_proof_single_vs_multi ... ok
```

You can go ahead to merge this PR, if some interesting thing found, I can paste into the  #1408 .

**Comment by garyyu** [comment]
It's clear now, my problem, sorry for the wrong remind.

Lucky you choose `chrono Utc::now()` to measure time, I was using `std::time::SystemTime`, now I know it's bad one:
```
        let now = SystemTime::now();
        ...
        if let Ok(elapsed) = now.elapsed() {
            let used_time = elapsed.as_secs();
            println!("spent time:\t{}(s)/({} verify)", used_time, LENGTH);
        }
```

**Comment by yeastplume** [comment]
Okay, will merge this now.. thanks for checking

**Comment by antiochp** [comment]
🚀

**Pull request merged**
