### PR TITLE
improve: time crate flagged as deprecated, switch to actively maintained chrono crate

### PR DESCRIPTION
**Pull request by garyyu**
As announced on time crate **repo name**:  github.com/**rust-lang-deprecated**/time and in its [README](https://github.com/rust-lang-deprecated/time/blob/master/README.md).

And It suggest go to more actively maintained **chrono** crate: https://github.com/chronotope/chrono

chrono `Datetime` usage is much more simple. 

If want it, please do a quick merge to avoid future merge conflict, since this pull-request touch 33 files.

### CODE REVIEW

**Comment by yeastplume** [comment]
Not against this in theory, but do `chrono` and `time` timestamps de/serialise exactly the same way? Need to be very sure about this, otherwise this breaks consensus.

**Comment by sesam** [comment]
I looked at this once, thinking chrono really is a huge dependency just for
timestamps. Though we likely already have third party dependencies on
chrono.

How about creating an internal grin-timestamp crate that wraps this
problem, and we start adding tests for serialization, then maybe later
implement our own methods onstead of time's, abd avoid depending on the
huge chrono everywhere?

**Comment by garyyu** [comment]
@yeastplume  tested, both running and mining are OK, also worry about the timestamps de/serialization before.

@sesam  as you thought, we already (not likely:) have third party dependencies on chrono.  search it please.

**Comment by ignopeverell** [comment]
Not against this either. At least if it all compiles :-) I've been annoyed more than once about inconsistencies between the `time` crate and `std::time`.

**Comment by garyyu** [comment]
I look into the travis-ci and just realize all the `test` folder had been left behind, don't know how this happened:)  will complete them soon.

**Comment by garyyu** [comment]
still have travis-ci errors on `chain` and `wallet` test, please hold.

**Comment by garyyu** [comment]
Finally! All `cargo test` passed and `Travis-CI` should be happy now.

[but, please check the Travis-CI config, the latest CI build has problem in env, not the pull-request code issue]:

`The command "sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"" failed and exited with 1 during .`

**Comment by yeastplume** [comment]
Was just usual Travis CI random failures. Will merge now and cross fingers.

**Pull request merged**
