### PR TITLE
Update Swedish intro.md

### PR DESCRIPTION
**Pull request by rsoltanzadeh**
Significant improvements, including a less excessive translation of the English terminology.

### CODE REVIEW

**Comment by lehnberg** [comment]
Tack för att du skickade in en PR! 

Please could you rename the commit and change the pull request description into something that's better describing the proposed change? Your Pull Request title: `Update Swedish intro.md`, would be suitable, for example.

**Comment by rsoltanzadeh** [comment]
Lol. I didn't realize that became the commit message. I'll try to figure out how to change it.

**Comment by rsoltanzadeh** [comment]
I'm unsure if I managed to fix it. Not familiar with the Github UI at all, @lehnberg.

**Comment by lehnberg** [comment]
Thanks @rsoltanzadeh - fixed now!

**Pull request merged**
