### PR TITLE
[T4 Update minimum share difficulty

### PR DESCRIPTION
**Pull request by quentinlesceller**
Update `minimal_share_difficulty` for stratum server. Use `consensus::MINIMUM_DIFFICULTY`.

### CODE REVIEW

**Comment by yeastplume** [comment]
It's a bit more complicated here in that grin-miner has no notion of secondary scaling, it's just returning the simple difficulty as calculated. So if this change is made, the adjusted difficulty needs to be communicated to grin-miner somehow, otherwise it will won't return any solutions under the (very high according to it) share difficulty.

**Comment by yeastplume** [comment]
Actually, looking through this again it might be okay. Can you just ensure grin-miner will run properly against the chain after this change before merging?

**Comment by quentinlesceller** [comment]
Sure. I'm doing some local testing now.

**Comment by ignopeverell** [comment]
I'm not sure we need this. There's no difficulty lower than 1 and at this point, the "any Cuckatoo solution is a share" behavior is prolly still what makes the most sense.

**Comment by quentinlesceller** [comment]
Okay in that case closing.

**Pull request closed without merging**
