### PR TITLE
infinite loops in check_orphans, if block in orphans has a forked parent

### PR DESCRIPTION
**Pull request by garyyu**
fix for https://github.com/mimblewimble/grin/issues/1451

### CODE REVIEW

**Comment by ignopeverell** [comment]
Looking at this for a bit, it seems that all orphans at a given height should get sent to the pipeline. So there shouldn't be any breaking or continue out of this loop, right? We never know in advance wich fork will be correct. And thanks for trying to fix my code :-)

**Comment by ignopeverell** [comment]
Sorry for being unclear, I was referring to your first bullet point. I don't think we should go to the next height if there are more orphans at the current one, as we don't know which will end up on the longest chain yet.

**Comment by garyyu** [comment]
Thanks, understand now.
will change code and give more test on it.

**Comment by garyyu** [comment]
@ignopeverell  fix is done, please help to check again.

Also I add some pretty log for us:
```
Sep 01 11:28:09.981 DEBG check_orphans: get block 15546fcb at 76394
Sep 01 11:28:09.999 DEBG check_orphans: get block 10281f11 at 76395
Sep 01 11:28:10.014 DEBG check_orphans: get block 0677ebf6 at 76396
Sep 01 11:28:10.033 DEBG check_orphans: get block 018de938 at 76397
Sep 01 11:28:10.050 DEBG check_orphans: get block 18dc3a5e at 76398
Sep 01 11:28:10.066 DEBG check_orphans: get block 02347c5a at 76399
Sep 01 11:28:10.084 DEBG check_orphans: get block 0c8ee9db at 76400
Sep 01 11:28:10.101 DEBG check_orphans: 7 blocks accepted since height 76394, remaining # orphans 12
Sep 01 11:28:10.339 DEBG check_orphans: get block 158192a7 at 76402
Sep 01 11:28:10.354 DEBG check_orphans: get block 110ad167 at 76403
Sep 01 11:28:10.371 DEBG check_orphans: get block 08b7517b at 76404
Sep 01 11:28:10.387 DEBG check_orphans: get block 158f0b02 at 76405
Sep 01 11:28:10.403 DEBG check_orphans: get block 0a11743c at 76406
Sep 01 11:28:10.419 DEBG check_orphans: get block 12bcfb12 at 76407
Sep 01 11:28:10.435 DEBG check_orphans: get block 07b3c90a at 76408
Sep 01 11:28:10.451 DEBG check_orphans: get block 1299ba2a at 76409
Sep 01 11:28:10.467 DEBG check_orphans: get block 077d71c9 at 76410
Sep 01 11:28:10.482 DEBG check_orphans: get block 0656f47b at 76411
Sep 01 11:28:10.497 DEBG check_orphans: get block 0b50aa40 at 76412
Sep 01 11:28:10.511 DEBG check_orphans: get block 03f98dc2 at 76413, no.0 of 2 orphans
Sep 01 11:28:10.527 DEBG check_orphans: get block 15ea486a at 76413, no.1 of 2 orphans
Sep 01 11:28:10.539 DEBG check_orphans: get block 02974e78 at 76414
Sep 01 11:28:10.558 DEBG check_orphans: 13 blocks accepted since height 76402, remaining # orphans 3
Sep 01 11:28:10.591 DEBG check_orphans: get block 1541ea7c at 76416
Sep 01 11:28:10.606 DEBG check_orphans: get block 0d3d75fb at 76417
Sep 01 11:28:10.621 DEBG check_orphans: get block 14155005 at 76418
Sep 01 11:28:10.638 DEBG check_orphans: 3 blocks accepted since height 76416, remaining # orphans 0
```

**Pull request merged**
