### PR TITLE
Rebased the wallet operator code

### PR DESCRIPTION
**Pull request by camalolo**
And hopefully this pull-request is more readable than my erhm... 3 previous ones. Sorry about that.

### CODE REVIEW

**Comment by ignopeverell** [comment]
Why did you end up closing this PR? Any issue?

**Comment by camalolo** [comment]
Hello sorry I did not see your question ! I wanted to re-organize my code better so it was easier to understand my pull request, and then I got quite busy on my day work, sorry about that. Maybe I can make a new pull request with my reorganized code ?

**Comment by sesam** [comment]
Hi! Of course. PR early, PR often :) Good so that all contributors see what you're working on.
If you have working code, fire away!
In general, possibly also in your case, it could be simpler to get through if the change is in a few smaller steps.

Changes like renames (utxos -> outputs, and utxo -> output) and preemptive refactorings are probably a good idea to start with. That woul be best practice, but maybe not strictly necessary - grin don't have any really strict policies yet.

**Comment by camalolo** [comment]
OK ! Thanks for your input ! I'll rebase, re-test and create a new PR :)

**Pull request closed without merging**
