### PR TITLE
replace is_mainnet() with !is_testnet()

### PR DESCRIPTION
**Pull request by antiochp**
This makes testing "mainnet" code significantly easier (its the default).

It also makes the various "hard fork" pieces of conditional logic easier to maintain and clearer in their intent.

Testing nodes locally in local "user testing mode" now defaults to mainnet hard fork logic (and not testnet4). i.e. no hard forks based on block height (yet).

The main driver of this was for test coverage around #2104 (sign kernel features) as we do not do this in testnet4 but we plan to do this in mainnet (and it would be good to actually test this).

----

TODO - 
- [x] investigate failing test
- [x] looks like we checked in some wallet db files (add to .gitignore)

### CODE REVIEW

**Comment by antiochp** [comment]
This change modifies the consensus rules when we're in "automated testing mode".
We default now to `mainnet` rules and not testnet4 (with HF) rules.

The following test is failing via `cargo test -p grin_core` - 

https://github.com/mimblewimble/grin/blob/2d4538c4281c6c169d2154694f2c21ebad582c9a/core/tests/consensus.rs#L392-L393

```
test next_target_adjustment ... FAILED

failures:

---- next_target_adjustment stdout ----
thread 'next_target_adjustment' panicked at 'assertion failed: `(left != right)`
  left: `3`,
 right: `3`', core/tests/consensus.rs:393:2
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    next_target_adjustment
```

So `secondary_scaling=3` and we test that it `3 != 3` and the test fails.

I do not know enough about the difficulty adjustment algorithm to know what needs changing/fixing here.

@tromp @ignopeverell 

Assuming we do want to run the tests against the `mainnet` consensus rules, what should we be testing here?

**Comment by antiochp** [comment]
@tromp It does look like this is related to the damping factor changes.

But I'm not sure this test is even doing anything useful.
We "repeat" a header_info 15 times to generate the difficulty iterator.

Pre-damping changes (using DIFFICULTY_DAMP_FACTOR) we see that the secondary scaling is always `4`, regardless of how many times we repeat the test header_info as part of the test setup - 

```
# DIFFICULTY_DAMP_FACTOR based test output for next_difficulty, based on various "repeat" numbers - 
1: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
2: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
3: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
4: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
5: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
6: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
7: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
8: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
9: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
10: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
11: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
12: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
13: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
14: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
15: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 4, is_secondary: false }
16: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
17: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
18: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
19: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
20: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
21: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
22: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
23: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
24: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
25: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
26: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
27: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
28: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
29: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
30: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
31: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 4, is_secondary: false }
```

```
# AR_SCALE_DAMP_FACTOR based test output for next_difficulty, based on various "repeat" numbers - 
1: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
2: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
3: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
4: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
5: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
6: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
7: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
8: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
9: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
10: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
11: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
12: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
13: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
14: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
15: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 4 }, secondary_scaling: 3, is_secondary: false }
16: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
17: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
18: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
19: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
20: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
21: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
22: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
23: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
24: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
25: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
26: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
27: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
28: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
29: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
30: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
31: HeaderInfo { timestamp: 1, difficulty: Difficulty { num: 3 }, secondary_scaling: 3, is_secondary: false }
```

Neither of these test what the comment suggests -
https://github.com/mimblewimble/grin/blob/2d4538c4281c6c169d2154694f2c21ebad582c9a/core/tests/consensus.rs#L392-L393

The original test (using `DIFFICULTY_DAMP_FACTOR`) is simply testing that `3 != 4` and there is nothing about "not getting stuck".

The test fails when using `AR_SCALE_DAMP_FACTOR` because the secondary_scaling value is always `3` in this test.

**Comment by tromp** [comment]
How did you get the output above? Several things confuse me. First, they start off with 15 blocks at diff 4. Where do the 4 and 15 come from? In the code

	let mut hi = HeaderInfo::from_diff_scaling(diff_min, MIN_DIFFICULTY as u32);
	hi.is_secondary = false;
	let hinext = next_difficulty(1, repeat(15, hi.clone(), DIFFICULTY_ADJUST_WINDOW, None));

MIN_DIFFICULTY is 3, and 15 is not the number of repeats but the interval in seconds, i.e. it should be written as BLOCK_TIME_SEC/4.

I think the tests do what is intended. The failing AR scale tests show that letting ar_scale drop below AR_DAMP_FACTOR - 1 is fatal. If the test sets hi.ar_scale to AR_DAMP_FACTOR, then it should pass.

**Comment by tromp** [comment]
So the code should be updated to

	let mut hi = HeaderInfo::from_diff_scaling(diff_min, AR_SCALE_DAMP_FACTOR as u32);
	hi.is_secondary = false;
	let hinext = next_difficulty(1, repeat(BLOCK_TIME_SEC/4, hi.clone(), DIFFICULTY_ADJUST_WINDOW, None));

**Pull request merged**
