### PR TITLE
Allow rest api to shutdown

### PR DESCRIPTION
**Pull request by i1skn**
I think we can re-enable this functionality, `grin-wallet` also uses this crate and it's good to have an ability to shutdown the api without killing the process.

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Looking good. Do you know why we can reenable this now?

**Comment by i1skn** [comment]
As far as I got after conversation with @hashmap there was a temporary bug in hyper version, which is now fixed. I've tested it as a part of Ironbelly and it shutdowns the API properly.

**Review by quentinlesceller — APPROVED** [review]
Tested and looking good. LGTM 👍

**Comment by quentinlesceller** [comment]
@i1skn seems like the API does not start with this change.

**Comment by i1skn** [comment]
Hi, is there any specific reason or case when it does not start?

**Comment by quentinlesceller** [comment]
Basically any call on the API will just fails. The server is not listening.

**Pull request merged**
