### PR TITLE
Add hex serialization functions

### PR DESCRIPTION
**Pull request by svechinsky**
Addressing https://github.com/mimblewimble/grin/issues/2134
Comments about everything are welcome.

### CODE REVIEW

**Comment by jaspervdm** [comment]
Note that this will break sending/receiving transactions between upgraded and non-upgraded wallets

**Comment by svechinsky** [comment]
hmmm overlooked this, will hopefully add checks tomorrow

**Comment by yeastplume** [comment]
Just looking through this in some more detail, as I think I'd like this in place before merging https://github.com/mimblewimble/grin/pull/2441 since I'd like to use the same serialization features there as well.

Can I suggest moving all of the serialization methods into their own separate module rather than spreading them around, perhaps in core/src/libtx for now (until we decide the best place to put it). I think it will be useful to have all these methods to sanely serialise libsecp primitives somewhere common. We may even want to split this PR into 2, with one to add the serialisation module and another to turn them on in a backwards compatible way. That would also help me move on with #2441

**Comment by svechinsky** [comment]
Ok, so:
1. Reorganize the serialization modules into a separate module.
2. Comment out the serde directives for activation at a later date

**Comment by yeastplume** [comment]
Yes, sounds like a good plan, thanks!

**Comment by svechinsky** [comment]
@yeastplume Just pinging for a review

**Comment by antiochp** [comment]
I'm not to enthusiastic about merging in commented out code like this.

We should either agree to keep this PR open and track it against master (not a huge fan of this either) or push forward on getting this done in a way that preserves backward compatibility.

**Comment by ignopeverell** [comment]
You already have custom serializers now, why not make them revert to the old representation on hex errors?

**Comment by svechinsky** [comment]
The problem is not with deserializing binary/hex but rather with serializing it so that old clients can accept them.

**Comment by yeastplume** [comment]
@svechinsky Right, we're going to have to take a decision at some point as to what to do about older wallets, obviously they won't be able to handle the new format and will choke rather gracelessly. Also, we should probably take the opportunity here to add a version ID to the slate to help us mitigate future problems, and ensure the wallet takes it into consideration (and keep a minimum version it can handle).

Unfortunately this has gone a little bit worm-canny. Can I suggest the following:

1) Remove the commented out directives, and just commit the serialization lib in this PR. (This will let me get on with #2441 as well)
2) Another PR for an optional Slate ID (and have to consider how this remains backwards compatible, given it would adds a field that doesn't exist in older clients)
3) Another PR to handle the integration of new slate + backwards compatibility concerns there

**Comment by svechinsky** [comment]
Ok, will sort out today/tomorrow, will def do 1 today so it won't block #2441

**Comment by yeastplume** [comment]
Okay, great thank you. Lib functions looks good as they are, so I'll merge.

**Pull request merged**
