### PR TITLE
Fix keychain to work with non-Copy secp::SecretKey

### PR DESCRIPTION
**Pull request by eupn**
This PR allows keychain to work with `secp::SecretKey` which made non-`Copy`able in https://github.com/mimblewimble/rust-secp256k1-zkp/pull/51

This fix should be merged as soon as https://github.com/mimblewimble/rust-secp256k1-zkp/pull/51 is.

*Update*: https://github.com/mimblewimble/rust-secp256k1-zkp/pull/51 is merged, so this PR can be merged as well.

### CODE REVIEW

**Comment by antiochp** [comment]
Why `Clone` and not `Copy`? What's the benefit?

**Comment by eupn** [comment]
@antiochp 
> Why `Clone` and not `Copy`? What's the benefit?

It is impossible to implement both `Copy` and `Drop`. Therefore, if one wants to use a custom implementation of `Drop` (which zeroes underlying data, for example), he should remove `Copy` derive. Since `Copy` trait is no longer implemented, the only option left is to use `.clone` to satisfy borrow-checker. Hope this makes sense.

**Comment by hashmap** [comment]
https://doc.rust-lang.org/1.30.0/book/2018-edition/ch04-01-what-is-ownership.html

If a type has the Copy trait, an older variable is still usable after assignment. Rust won’t let us annotate a type with the Copy trait if the type, or any of its parts, has implemented the Drop trait. If the type needs something special to happen when the value goes out of scope and we add the Copy annotation to that type, we’ll get a compile time error.

**Comment by garyyu** [comment]
Similar comment as in https://github.com/mimblewimble/grin-wallet/pull/121#issuecomment-497533632

**Comment by garyyu** [comment]
Related:  https://github.com/mimblewimble/grin/pull/2847#issuecomment-499268857

**Comment by yeastplume** [comment]
the PR in rust-secp256k1 may have been merged, but a new version hasn't been released. @jaspervdm I assume this will need to go in for 2.0.0 when we do a new release of rust-secp for all of the other 2.0.0 changes?

**Comment by jaspervdm** [comment]
If it has been merged in rust-secp already then yes we need this for v2.0.0

**Comment by yeastplume** [comment]
Fixed via #2848

**Pull request closed without merging**
